// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.le.AdvertiseSettings", implements: Parcelable.self)
open class AdvertiseSettings: JavaObject {
  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func isConnectable() -> Bool

  @JavaMethod
  open func isDiscoverable() -> Bool

  @JavaMethod
  open func getTxPowerLevel() -> Int32

  @JavaMethod
  open func getMode() -> Int32

  @JavaMethod
  open func getTimeout() -> Int32

  @JavaMethod
  open override func toString() -> String
}
extension JavaClass<AdvertiseSettings> {
  @JavaStaticField(isFinal: true)
  public var ADVERTISE_MODE_BALANCED: Int32

  @JavaStaticField(isFinal: true)
  public var ADVERTISE_MODE_LOW_LATENCY: Int32

  @JavaStaticField(isFinal: true)
  public var ADVERTISE_MODE_LOW_POWER: Int32

  @JavaStaticField(isFinal: true)
  public var ADVERTISE_TX_POWER_HIGH: Int32

  @JavaStaticField(isFinal: true)
  public var ADVERTISE_TX_POWER_LOW: Int32

  @JavaStaticField(isFinal: true)
  public var ADVERTISE_TX_POWER_MEDIUM: Int32

  @JavaStaticField(isFinal: true)
  public var ADVERTISE_TX_POWER_ULTRA_LOW: Int32

  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<AdvertiseSettings>!

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
