// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import AndroidUtil
import JavaKit
import JavaKitCollection
import JavaRuntime
import JavaUtil

@JavaClass("android.bluetooth.le.AdvertiseData", implements: Parcelable.self)
open class AdvertiseData: JavaObject {
  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func getServiceUuids() -> List<ParcelUuid>!

  @JavaMethod
  open func getServiceData() -> Map<ParcelUuid, JavaArray>!

  @JavaMethod
  open func getServiceSolicitationUuids() -> List<ParcelUuid>!

  @JavaMethod
  open func getManufacturerSpecificData() -> SparseArray<JavaArray>!

  @JavaMethod
  open func getTransportDiscoveryData() -> List<TransportDiscoveryData>!

  @JavaMethod
  open func getIncludeTxPowerLevel() -> Bool

  @JavaMethod
  open func getIncludeDeviceName() -> Bool

  @JavaMethod
  open override func equals(_ arg0: AdvertiseData?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32
}
extension JavaClass<AdvertiseData> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<AdvertiseData>!

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}

extension AdvertiseData: CustomStringConvertible {
    
    public var description: String {
        toString()
    }
}
