// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.le.AdvertisingSetCallback")
open class AdvertisingSetCallback: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func onPeriodicAdvertisingParametersUpdated(_ arg0: AdvertisingSet?, _ arg1: Int32)

  @JavaMethod
  open func onAdvertisingSetStarted(_ arg0: AdvertisingSet?, _ arg1: Int32, _ arg2: Int32)

  @JavaMethod
  open func onAdvertisingSetStopped(_ arg0: AdvertisingSet?)

  @JavaMethod
  open func onAdvertisingEnabled(_ arg0: AdvertisingSet?, _ arg1: Bool, _ arg2: Int32)

  @JavaMethod
  open func onAdvertisingDataSet(_ arg0: AdvertisingSet?, _ arg1: Int32)

  @JavaMethod
  open func onScanResponseDataSet(_ arg0: AdvertisingSet?, _ arg1: Int32)

  @JavaMethod
  open func onAdvertisingParametersUpdated(_ arg0: AdvertisingSet?, _ arg1: Int32, _ arg2: Int32)

  @JavaMethod
  open func onPeriodicAdvertisingDataSet(_ arg0: AdvertisingSet?, _ arg1: Int32)

  @JavaMethod
  open func onPeriodicAdvertisingEnabled(_ arg0: AdvertisingSet?, _ arg1: Bool, _ arg2: Int32)
}
extension JavaClass<AdvertisingSetCallback> {
  @JavaStaticField(isFinal: true)
  public var ADVERTISE_FAILED_ALREADY_STARTED: Int32

  @JavaStaticField(isFinal: true)
  public var ADVERTISE_FAILED_DATA_TOO_LARGE: Int32

  @JavaStaticField(isFinal: true)
  public var ADVERTISE_FAILED_FEATURE_UNSUPPORTED: Int32

  @JavaStaticField(isFinal: true)
  public var ADVERTISE_FAILED_INTERNAL_ERROR: Int32

  @JavaStaticField(isFinal: true)
  public var ADVERTISE_FAILED_TOO_MANY_ADVERTISERS: Int32

  @JavaStaticField(isFinal: true)
  public var ADVERTISE_SUCCESS: Int32
}
