// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension AdvertiseSettings {
  @JavaClass("android.bluetooth.le.AdvertiseSettings$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func setAdvertiseMode(_ arg0: Int32) throws -> AdvertiseSettings.Builder!

  @JavaMethod
  open func setTxPowerLevel(_ arg0: Int32) throws -> AdvertiseSettings.Builder!

  @JavaMethod
  open func setConnectable(_ arg0: Bool) -> AdvertiseSettings.Builder!

  @JavaMethod
  open func setDiscoverable(_ arg0: Bool) -> AdvertiseSettings.Builder!

  @JavaMethod
  open func setTimeout(_ arg0: Int32) throws -> AdvertiseSettings.Builder!

  @JavaMethod
  open func build() -> AdvertiseSettings!
  }
}
