// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("android.bluetooth.le.AdvertiseCallback")
open class AdvertiseCallback: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func onStartSuccess(_ arg0: AdvertiseSettings?)

  @JavaMethod
  open func onStartFailure(_ arg0: Int32)
}
extension JavaClass<AdvertiseCallback> {
  @JavaStaticField(isFinal: true)
  public var ADVERTISE_FAILED_ALREADY_STARTED: Int32

  @JavaStaticField(isFinal: true)
  public var ADVERTISE_FAILED_DATA_TOO_LARGE: Int32

  @JavaStaticField(isFinal: true)
  public var ADVERTISE_FAILED_FEATURE_UNSUPPORTED: Int32

  @JavaStaticField(isFinal: true)
  public var ADVERTISE_FAILED_INTERNAL_ERROR: Int32

  @JavaStaticField(isFinal: true)
  public var ADVERTISE_FAILED_TOO_MANY_ADVERTISERS: Int32
}
