// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaKit
import JavaRuntime

@JavaClass("android.bluetooth.le.AdvertisingSetParameters", implements: Parcelable.self)
open class AdvertisingSetParameters: JavaObject {
  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func isConnectable() -> Bool

  @JavaMethod
  open func isDiscoverable() -> Bool

  @JavaMethod
  open func isScannable() -> Bool

  @JavaMethod
  open func isLegacy() -> Bool

  @JavaMethod
  open func isAnonymous() -> Bool

  @JavaMethod
  open func includeTxPower() -> Bool

  @JavaMethod
  open func getPrimaryPhy() -> Int32

  @JavaMethod
  open func getSecondaryPhy() -> Int32

  @JavaMethod
  open func getInterval() -> Int32

  @JavaMethod
  open func getTxPowerLevel() -> Int32

  @JavaMethod
  open override func toString() -> String
}
extension JavaClass<AdvertisingSetParameters> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<AdvertisingSetParameters>!

  @JavaStaticField(isFinal: true)
  public var INTERVAL_HIGH: Int32

  @JavaStaticField(isFinal: true)
  public var INTERVAL_LOW: Int32

  @JavaStaticField(isFinal: true)
  public var INTERVAL_MAX: Int32

  @JavaStaticField(isFinal: true)
  public var INTERVAL_MEDIUM: Int32

  @JavaStaticField(isFinal: true)
  public var INTERVAL_MIN: Int32

  @JavaStaticField(isFinal: true)
  public var TX_POWER_HIGH: Int32

  @JavaStaticField(isFinal: true)
  public var TX_POWER_LOW: Int32

  @JavaStaticField(isFinal: true)
  public var TX_POWER_MAX: Int32

  @JavaStaticField(isFinal: true)
  public var TX_POWER_MEDIUM: Int32

  @JavaStaticField(isFinal: true)
  public var TX_POWER_MIN: Int32

  @JavaStaticField(isFinal: true)
  public var TX_POWER_ULTRA_LOW: Int32

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
