// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.le.AdvertisingSet")
open class AdvertisingSet: JavaObject {
  @JavaMethod
  open func enableAdvertising(_ arg0: Bool, _ arg1: Int32, _ arg2: Int32)

  @JavaMethod
  open func setAdvertisingData(_ arg0: AdvertiseData?)

  @JavaMethod
  open func setScanResponseData(_ arg0: AdvertiseData?)

  @JavaMethod
  open func setAdvertisingParameters(_ arg0: AdvertisingSetParameters?)

  @JavaMethod
  open func setPeriodicAdvertisingParameters(_ arg0: PeriodicAdvertisingParameters?)

  @JavaMethod
  open func setPeriodicAdvertisingData(_ arg0: AdvertiseData?)

  @JavaMethod
  open func setPeriodicAdvertisingEnabled(_ arg0: Bool)
}
