// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension AdvertisingSetParameters {
  @JavaClass("android.bluetooth.le.AdvertisingSetParameters$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func setTxPowerLevel(_ arg0: Int32) -> AdvertisingSetParameters.Builder!

  @JavaMethod
  open func setConnectable(_ arg0: Bool) -> AdvertisingSetParameters.Builder!

  @JavaMethod
  open func setDiscoverable(_ arg0: Bool) -> AdvertisingSetParameters.Builder!

  @JavaMethod
  open func setScannable(_ arg0: Bool) -> AdvertisingSetParameters.Builder!

  @JavaMethod
  open func setLegacyMode(_ arg0: Bool) -> AdvertisingSetParameters.Builder!

  @JavaMethod
  open func setAnonymous(_ arg0: Bool) -> AdvertisingSetParameters.Builder!

  @JavaMethod
  open func setIncludeTxPower(_ arg0: Bool) -> AdvertisingSetParameters.Builder!

  @JavaMethod
  open func setPrimaryPhy(_ arg0: Int32) -> AdvertisingSetParameters.Builder!

  @JavaMethod
  open func setSecondaryPhy(_ arg0: Int32) -> AdvertisingSetParameters.Builder!

  @JavaMethod
  open func setInterval(_ arg0: Int32) -> AdvertisingSetParameters.Builder!

  @JavaMethod
  open func build() -> AdvertisingSetParameters!
  }
}
