// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.BluetoothHeadset", implements: BluetoothProfile.self)
open class BluetoothHeadset: JavaObject {
  @JavaMethod
  open func getConnectionState(_ arg0: BluetoothDevice?) -> Int32

  @JavaMethod
  open func isAudioConnected(_ arg0: BluetoothDevice?) -> Bool

  @JavaMethod
  open func getConnectedDevices() -> List<BluetoothDevice>!

  @JavaMethod
  open func getDevicesMatchingConnectionStates(_ arg0: [Int32]) -> List<BluetoothDevice>!

  @JavaMethod
  open func isNoiseReductionSupported(_ arg0: BluetoothDevice?) -> Bool

  @JavaMethod
  open func isVoiceRecognitionSupported(_ arg0: BluetoothDevice?) -> Bool

  @JavaMethod
  open func startVoiceRecognition(_ arg0: BluetoothDevice?) -> Bool

  @JavaMethod
  open func stopVoiceRecognition(_ arg0: BluetoothDevice?) -> Bool

  @JavaMethod
  open func sendVendorSpecificResultCode(_ arg0: BluetoothDevice?, _ arg1: String, _ arg2: String) -> Bool

  @JavaMethod
  open override func finalize() throws
}
extension JavaClass<BluetoothHeadset> {
  @JavaStaticField(isFinal: true)
  public var ACTION_AUDIO_STATE_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_CONNECTION_STATE_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_VENDOR_SPECIFIC_HEADSET_EVENT: String

  @JavaStaticField(isFinal: true)
  public var AT_CMD_TYPE_ACTION: Int32

  @JavaStaticField(isFinal: true)
  public var AT_CMD_TYPE_BASIC: Int32

  @JavaStaticField(isFinal: true)
  public var AT_CMD_TYPE_READ: Int32

  @JavaStaticField(isFinal: true)
  public var AT_CMD_TYPE_SET: Int32

  @JavaStaticField(isFinal: true)
  public var AT_CMD_TYPE_TEST: Int32

  @JavaStaticField(isFinal: true)
  public var EXTRA_VENDOR_SPECIFIC_HEADSET_EVENT_ARGS: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_VENDOR_SPECIFIC_HEADSET_EVENT_CMD: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_VENDOR_SPECIFIC_HEADSET_EVENT_CMD_TYPE: String

  @JavaStaticField(isFinal: true)
  public var STATE_AUDIO_CONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_AUDIO_CONNECTING: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_AUDIO_DISCONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var VENDOR_RESULT_CODE_COMMAND_ANDROID: String

  @JavaStaticField(isFinal: true)
  public var VENDOR_SPECIFIC_HEADSET_EVENT_COMPANY_ID_CATEGORY: String

  @JavaStaticField(isFinal: true)
  public var A2DP: Int32

  @JavaStaticField(isFinal: true)
  public var CSIP_SET_COORDINATOR: Int32

  @JavaStaticField(isFinal: true)
  public var EXTRA_PREVIOUS_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_STATE: String

  @JavaStaticField(isFinal: true)
  public var GATT: Int32

  @JavaStaticField(isFinal: true)
  public var GATT_SERVER: Int32

  @JavaStaticField(isFinal: true)
  public var HAP_CLIENT: Int32

  @JavaStaticField(isFinal: true)
  public var HEADSET: Int32

  @JavaStaticField(isFinal: true)
  public var HEALTH: Int32

  @JavaStaticField(isFinal: true)
  public var HEARING_AID: Int32

  @JavaStaticField(isFinal: true)
  public var HID_DEVICE: Int32

  @JavaStaticField(isFinal: true)
  public var LE_AUDIO: Int32

  @JavaStaticField(isFinal: true)
  public var SAP: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CONNECTING: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_DISCONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_DISCONNECTING: Int32
}
