// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("android.bluetooth.BluetoothCodecStatus", implements: Parcelable.self)
open class BluetoothCodecStatus: JavaObject {
  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func getCodecConfig() -> BluetoothCodecConfig!

  @JavaMethod
  open func isCodecConfigSelectable(_ arg0: BluetoothCodecConfig?) -> Bool

  @JavaMethod
  open func getCodecsLocalCapabilities() -> List<BluetoothCodecConfig>!

  @JavaMethod
  open func getCodecsSelectableCapabilities() -> List<BluetoothCodecConfig>!

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32
}
extension JavaClass<BluetoothCodecStatus> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<BluetoothCodecStatus>!

  @JavaStaticField(isFinal: true)
  public var EXTRA_CODEC_STATUS: String

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
