// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.BluetoothManager")
open class BluetoothManager: JavaObject {
  @JavaMethod
  open func getConnectionState(_ arg0: BluetoothDevice?, _ arg1: Int32) -> Int32

  @JavaMethod
  open func openGattServer(_ arg0: Context?, _ arg1: BluetoothGattServerCallback?) -> BluetoothGattServer!

  @JavaMethod
  open func getConnectedDevices(_ arg0: Int32) -> List<BluetoothDevice>!

  @JavaMethod
  open func getDevicesMatchingConnectionStates(_ arg0: Int32, _ arg1: [Int32]) -> List<BluetoothDevice>!

  @JavaMethod
  open func getAdapter() -> BluetoothAdapter!
}
