// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.BluetoothHealth", implements: BluetoothProfile.self)
open class BluetoothHealth: JavaObject {
  @JavaMethod
  open func getConnectionState(_ arg0: BluetoothDevice?) -> Int32

  @JavaMethod
  open func disconnectChannel(_ arg0: BluetoothDevice?, _ arg1: BluetoothHealthAppConfiguration?, _ arg2: Int32) -> Bool

  @JavaMethod
  open func getMainChannelFd(_ arg0: BluetoothDevice?, _ arg1: BluetoothHealthAppConfiguration?) -> ParcelFileDescriptor!

  @JavaMethod
  open func getConnectedDevices() -> List<BluetoothDevice>!

  @JavaMethod
  open func getDevicesMatchingConnectionStates(_ arg0: [Int32]) -> List<BluetoothDevice>!

  @JavaMethod
  open func registerSinkAppConfiguration(_ arg0: String, _ arg1: Int32, _ arg2: BluetoothHealthCallback?) -> Bool

  @JavaMethod
  open func unregisterAppConfiguration(_ arg0: BluetoothHealthAppConfiguration?) -> Bool

  @JavaMethod
  open func connectChannelToSource(_ arg0: BluetoothDevice?, _ arg1: BluetoothHealthAppConfiguration?) -> Bool
}
extension JavaClass<BluetoothHealth> {
  @JavaStaticField(isFinal: true)
  public var APP_CONFIG_REGISTRATION_FAILURE: Int32

  @JavaStaticField(isFinal: true)
  public var APP_CONFIG_REGISTRATION_SUCCESS: Int32

  @JavaStaticField(isFinal: true)
  public var APP_CONFIG_UNREGISTRATION_FAILURE: Int32

  @JavaStaticField(isFinal: true)
  public var APP_CONFIG_UNREGISTRATION_SUCCESS: Int32

  @JavaStaticField(isFinal: true)
  public var CHANNEL_TYPE_RELIABLE: Int32

  @JavaStaticField(isFinal: true)
  public var CHANNEL_TYPE_STREAMING: Int32

  @JavaStaticField(isFinal: true)
  public var SINK_ROLE: Int32

  @JavaStaticField(isFinal: true)
  public var SOURCE_ROLE: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CHANNEL_CONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CHANNEL_CONNECTING: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CHANNEL_DISCONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CHANNEL_DISCONNECTING: Int32

  @JavaStaticField(isFinal: true)
  public var A2DP: Int32

  @JavaStaticField(isFinal: true)
  public var CSIP_SET_COORDINATOR: Int32

  @JavaStaticField(isFinal: true)
  public var EXTRA_PREVIOUS_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_STATE: String

  @JavaStaticField(isFinal: true)
  public var GATT: Int32

  @JavaStaticField(isFinal: true)
  public var GATT_SERVER: Int32

  @JavaStaticField(isFinal: true)
  public var HAP_CLIENT: Int32

  @JavaStaticField(isFinal: true)
  public var HEADSET: Int32

  @JavaStaticField(isFinal: true)
  public var HEALTH: Int32

  @JavaStaticField(isFinal: true)
  public var HEARING_AID: Int32

  @JavaStaticField(isFinal: true)
  public var HID_DEVICE: Int32

  @JavaStaticField(isFinal: true)
  public var LE_AUDIO: Int32

  @JavaStaticField(isFinal: true)
  public var SAP: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CONNECTING: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_DISCONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_DISCONNECTING: Int32
}
