// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension BluetoothHidDevice {
  @JavaClass("android.bluetooth.BluetoothHidDevice$Callback")
  open class Callback: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func onAppStatusChanged(_ arg0: BluetoothDevice?, _ arg1: Bool)

  @JavaMethod
  open func onGetReport(_ arg0: BluetoothDevice?, _ arg1: Int8, _ arg2: Int8, _ arg3: Int32)

  @JavaMethod
  open func onSetReport(_ arg0: BluetoothDevice?, _ arg1: Int8, _ arg2: Int8, _ arg3: [Int8])

  @JavaMethod
  open func onSetProtocol(_ arg0: BluetoothDevice?, _ arg1: Int8)

  @JavaMethod
  open func onInterruptData(_ arg0: BluetoothDevice?, _ arg1: Int8, _ arg2: [Int8])

  @JavaMethod
  open func onConnectionStateChanged(_ arg0: BluetoothDevice?, _ arg1: Int32)

  @JavaMethod
  open func onVirtualCableUnplug(_ arg0: BluetoothDevice?)
  }
}
