// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.BluetoothCodecType", implements: Parcelable.self)
open class BluetoothCodecType: JavaObject {
  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func isMandatoryCodec() -> Bool

  @JavaMethod
  open func getCodecId() -> Int64

  @JavaMethod
  open func getCodecName() -> String

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32
}
extension JavaClass<BluetoothCodecType> {
  @JavaStaticField(isFinal: true)
  public var CODEC_ID_AAC: Int64

  @JavaStaticField(isFinal: true)
  public var CODEC_ID_APTX: Int64

  @JavaStaticField(isFinal: true)
  public var CODEC_ID_APTX_HD: Int64

  @JavaStaticField(isFinal: true)
  public var CODEC_ID_LDAC: Int64

  @JavaStaticField(isFinal: true)
  public var CODEC_ID_OPUS: Int64

  @JavaStaticField(isFinal: true)
  public var CODEC_ID_SBC: Int64

  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<BluetoothCodecType>!

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
