// Auto-generated by Java-to-Swift wrapper generator.
import AndroidApp
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.le.BluetoothLeScanner")
open class BluetoothLeScanner: JavaObject {
  @JavaMethod
  open func startScan(_ arg0: List<ScanFilter>?, _ arg1: ScanSettings?, _ arg2: ScanCallback?) throws

  @JavaMethod
  open func startScan(_ arg0: ScanCallback?) throws

  @JavaMethod
  open func startScan(_ arg0: List<ScanFilter>?, _ arg1: ScanSettings?, _ arg2: PendingIntent?) throws -> Int32

  @JavaMethod
  open func stopScan(_ arg0: PendingIntent?) throws

  @JavaMethod
  open func stopScan(_ arg0: ScanCallback?) throws

  @JavaMethod
  open func flushPendingScanResults(_ arg0: ScanCallback?) throws
}
extension JavaClass<BluetoothLeScanner> {
  @JavaStaticField(isFinal: true)
  public var EXTRA_CALLBACK_TYPE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_ERROR_CODE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_LIST_SCAN_RESULT: String
}
