// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import SwiftJava
import CSwiftJavaJNI
import JavaTime
import JavaUtil
import JavaLangUtil

@JavaClass("android.bluetooth.BluetoothAdapter")
open class BluetoothAdapter: JavaObject {
  @JavaMethod
  open func getRemoteDevice(_ arg0: [Int8]) throws -> BluetoothDevice!

  @JavaMethod
  open func getRemoteDevice(_ arg0: String) throws -> BluetoothDevice!

  @JavaMethod
  open func getRemoteLeDevice(_ arg0: String, _ arg1: Int32) throws -> BluetoothDevice!

  @JavaMethod
  open func disable() -> Bool

  @JavaMethod
  open func getScanMode() -> Int32

  @JavaMethod
  open func startDiscovery() -> Bool

  @JavaMethod
  open func cancelDiscovery() -> Bool

  @JavaMethod
  open func isDiscovering() -> Bool

  @JavaMethod
  open func isLe2MPhySupported() -> Bool

  @JavaMethod
  open func isLeAudioSupported() -> Int32

  @JavaMethod
  open func getBondedDevices() -> JavaSet<BluetoothDevice>!

  @JavaMethod
  open func getProfileProxy(_ arg0: Context?, _ arg1: BluetoothProfile.ServiceListener?, _ arg2: Int32) -> Bool

  @JavaMethod
  open func closeProfileProxy(_ arg0: Int32, _ arg1: BluetoothProfile?)

  @JavaMethod
  open func startLeScan(_ arg0: [UUID?], _ arg1: BluetoothAdapter.LeScanCallback?) -> Bool

  @JavaMethod
  open func startLeScan(_ arg0: BluetoothAdapter.LeScanCallback?) -> Bool

  @JavaMethod
  open func stopLeScan(_ arg0: BluetoothAdapter.LeScanCallback?)

  @JavaMethod
  open func getBluetoothLeAdvertiser() -> BluetoothLeAdvertiser!

  @JavaMethod
  open func getBluetoothLeScanner() -> BluetoothLeScanner!

  @JavaMethod
  open func getDiscoverableTimeout() -> Duration!

  @JavaMethod
  open func isMultipleAdvertisementSupported() -> Bool

  @JavaMethod
  open func isOffloadedFilteringSupported() -> Bool

  @JavaMethod
  open func isOffloadedScanBatchingSupported() -> Bool

  @JavaMethod
  open func isLeCodedPhySupported() -> Bool

  @JavaMethod
  open func isLeExtendedAdvertisingSupported() -> Bool

  @JavaMethod
  open func isLePeriodicAdvertisingSupported() -> Bool

  @JavaMethod
  open func isLeAudioBroadcastSourceSupported() -> Int32

  @JavaMethod
  open func getLeMaximumAdvertisingDataLength() -> Int32

  @JavaMethod
  open func getMaxConnectedAudioDevices() -> Int32

  @JavaMethod
  open func getProfileConnectionState(_ arg0: Int32) -> Int32

  @JavaMethod
  open func listenUsingRfcommWithServiceRecord(_ arg0: String, _ arg1: UUID?) throws -> BluetoothServerSocket!

  @JavaMethod
  open func listenUsingL2capChannel() throws -> BluetoothServerSocket!

  @JavaMethod
  open func listenUsingInsecureL2capChannel() throws -> BluetoothServerSocket!

  @JavaMethod
  open func isLeAudioBroadcastAssistantSupported() -> Int32

  @JavaMethod
  open func listenUsingInsecureRfcommWithServiceRecord(_ arg0: String, _ arg1: UUID?) throws -> BluetoothServerSocket!

  @JavaMethod
  open func getName() -> String

  @JavaMethod
  open override func finalize() throws

  @JavaMethod
  open func isEnabled() -> Bool

  @JavaMethod
  open func setName(_ arg0: String) -> Bool

  @JavaMethod
  open func getState() -> Int32

  @JavaMethod
  open func getAddress() -> String

  @JavaMethod
  open func enable() -> Bool
}
extension JavaClass<BluetoothAdapter> {
  @JavaStaticField(isFinal: true)
  public var ACTION_CONNECTION_STATE_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_DISCOVERY_FINISHED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_DISCOVERY_STARTED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_LOCAL_NAME_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_REQUEST_DISCOVERABLE: String

  @JavaStaticField(isFinal: true)
  public var ACTION_REQUEST_ENABLE: String

  @JavaStaticField(isFinal: true)
  public var ACTION_SCAN_MODE_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_STATE_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ERROR: Int32

  @JavaStaticField(isFinal: true)
  public var EXTRA_CONNECTION_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_DISCOVERABLE_DURATION: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_LOCAL_NAME: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PREVIOUS_CONNECTION_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PREVIOUS_SCAN_MODE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PREVIOUS_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_SCAN_MODE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_STATE: String

  @JavaStaticField(isFinal: true)
  public var SCAN_MODE_CONNECTABLE: Int32

  @JavaStaticField(isFinal: true)
  public var SCAN_MODE_CONNECTABLE_DISCOVERABLE: Int32

  @JavaStaticField(isFinal: true)
  public var SCAN_MODE_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CONNECTING: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_DISCONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_DISCONNECTING: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_OFF: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_ON: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_TURNING_OFF: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_TURNING_ON: Int32

  @JavaStaticMethod
  public func getDefaultAdapter() -> BluetoothAdapter!

  @JavaStaticMethod
  public func checkBluetoothAddress(_ arg0: String) -> Bool
}
