// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.BluetoothHidDeviceAppSdpSettings", implements: Parcelable.self)
open class BluetoothHidDeviceAppSdpSettings: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, _ arg2: String, _ arg3: Int8, _ arg4: [Int8], environment: JNIEnvironment? = nil)

  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func getDescription() -> String

  @JavaMethod
  open func getSubclass() -> Int8

  @JavaMethod
  open func getDescriptors() -> [Int8]

  @JavaMethod
  open func getName() -> String

  @JavaMethod
  open func getProvider() -> String
}
extension JavaClass<BluetoothHidDeviceAppSdpSettings> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<BluetoothHidDeviceAppSdpSettings>!

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
