// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension BluetoothClass {
  @JavaClass("android.bluetooth.BluetoothClass$Device")
  open class Device: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
  }
}
extension JavaClass<BluetoothClass.Device> {
  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_CAMCORDER: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_CAR_AUDIO: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_HANDSFREE: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_HEADPHONES: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_HIFI_AUDIO: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_LOUDSPEAKER: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_MICROPHONE: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_PORTABLE_AUDIO: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_SET_TOP_BOX: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_UNCATEGORIZED: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_VCR: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_VIDEO_CAMERA: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_VIDEO_CONFERENCING: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_VIDEO_DISPLAY_AND_LOUDSPEAKER: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_VIDEO_GAMING_TOY: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_VIDEO_MONITOR: Int32

  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO_WEARABLE_HEADSET: Int32

  @JavaStaticField(isFinal: true)
  public var COMPUTER_DESKTOP: Int32

  @JavaStaticField(isFinal: true)
  public var COMPUTER_HANDHELD_PC_PDA: Int32

  @JavaStaticField(isFinal: true)
  public var COMPUTER_LAPTOP: Int32

  @JavaStaticField(isFinal: true)
  public var COMPUTER_PALM_SIZE_PC_PDA: Int32

  @JavaStaticField(isFinal: true)
  public var COMPUTER_SERVER: Int32

  @JavaStaticField(isFinal: true)
  public var COMPUTER_UNCATEGORIZED: Int32

  @JavaStaticField(isFinal: true)
  public var COMPUTER_WEARABLE: Int32

  @JavaStaticField(isFinal: true)
  public var HEALTH_BLOOD_PRESSURE: Int32

  @JavaStaticField(isFinal: true)
  public var HEALTH_DATA_DISPLAY: Int32

  @JavaStaticField(isFinal: true)
  public var HEALTH_GLUCOSE: Int32

  @JavaStaticField(isFinal: true)
  public var HEALTH_PULSE_OXIMETER: Int32

  @JavaStaticField(isFinal: true)
  public var HEALTH_PULSE_RATE: Int32

  @JavaStaticField(isFinal: true)
  public var HEALTH_THERMOMETER: Int32

  @JavaStaticField(isFinal: true)
  public var HEALTH_UNCATEGORIZED: Int32

  @JavaStaticField(isFinal: true)
  public var HEALTH_WEIGHING: Int32

  @JavaStaticField(isFinal: true)
  public var PERIPHERAL_KEYBOARD: Int32

  @JavaStaticField(isFinal: true)
  public var PERIPHERAL_KEYBOARD_POINTING: Int32

  @JavaStaticField(isFinal: true)
  public var PERIPHERAL_NON_KEYBOARD_NON_POINTING: Int32

  @JavaStaticField(isFinal: true)
  public var PERIPHERAL_POINTING: Int32

  @JavaStaticField(isFinal: true)
  public var PHONE_CELLULAR: Int32

  @JavaStaticField(isFinal: true)
  public var PHONE_CORDLESS: Int32

  @JavaStaticField(isFinal: true)
  public var PHONE_ISDN: Int32

  @JavaStaticField(isFinal: true)
  public var PHONE_MODEM_OR_GATEWAY: Int32

  @JavaStaticField(isFinal: true)
  public var PHONE_SMART: Int32

  @JavaStaticField(isFinal: true)
  public var PHONE_UNCATEGORIZED: Int32

  @JavaStaticField(isFinal: true)
  public var TOY_CONTROLLER: Int32

  @JavaStaticField(isFinal: true)
  public var TOY_DOLL_ACTION_FIGURE: Int32

  @JavaStaticField(isFinal: true)
  public var TOY_GAME: Int32

  @JavaStaticField(isFinal: true)
  public var TOY_ROBOT: Int32

  @JavaStaticField(isFinal: true)
  public var TOY_UNCATEGORIZED: Int32

  @JavaStaticField(isFinal: true)
  public var TOY_VEHICLE: Int32

  @JavaStaticField(isFinal: true)
  public var WEARABLE_GLASSES: Int32

  @JavaStaticField(isFinal: true)
  public var WEARABLE_HELMET: Int32

  @JavaStaticField(isFinal: true)
  public var WEARABLE_JACKET: Int32

  @JavaStaticField(isFinal: true)
  public var WEARABLE_PAGER: Int32

  @JavaStaticField(isFinal: true)
  public var WEARABLE_UNCATEGORIZED: Int32

  @JavaStaticField(isFinal: true)
  public var WEARABLE_WRIST_WATCH: Int32
}
