// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension BluetoothProfile {
  @JavaInterface("android.bluetooth.BluetoothProfile$ServiceListener")
  public struct ServiceListener {
  @JavaMethod
  public func onServiceConnected(_ arg0: Int32, _ arg1: BluetoothProfile?)

  @JavaMethod
  public func onServiceDisconnected(_ arg0: Int32)
  }
}
