// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.BluetoothLeAudioCodecConfig", implements: Parcelable.self)
open class BluetoothLeAudioCodecConfig: JavaObject {
  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func getCodecType() -> Int32

  @JavaMethod
  open func getCodecPriority() -> Int32

  @JavaMethod
  open func getSampleRate() -> Int32

  @JavaMethod
  open func getBitsPerSample() -> Int32

  @JavaMethod
  open func getCodecName() -> String

  @JavaMethod
  open func getChannelCount() -> Int32

  @JavaMethod
  open func getFrameDuration() -> Int32

  @JavaMethod
  open func getOctetsPerFrame() -> Int32

  @JavaMethod
  open func getMinOctetsPerFrame() -> Int32

  @JavaMethod
  open func getMaxOctetsPerFrame() -> Int32

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32
}
extension JavaClass<BluetoothLeAudioCodecConfig> {
  @JavaStaticField(isFinal: true)
  public var BITS_PER_SAMPLE_16: Int32

  @JavaStaticField(isFinal: true)
  public var BITS_PER_SAMPLE_24: Int32

  @JavaStaticField(isFinal: true)
  public var BITS_PER_SAMPLE_32: Int32

  @JavaStaticField(isFinal: true)
  public var BITS_PER_SAMPLE_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var CHANNEL_COUNT_1: Int32

  @JavaStaticField(isFinal: true)
  public var CHANNEL_COUNT_2: Int32

  @JavaStaticField(isFinal: true)
  public var CHANNEL_COUNT_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var CODEC_PRIORITY_DEFAULT: Int32

  @JavaStaticField(isFinal: true)
  public var CODEC_PRIORITY_DISABLED: Int32

  @JavaStaticField(isFinal: true)
  public var CODEC_PRIORITY_HIGHEST: Int32

  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<BluetoothLeAudioCodecConfig>!

  @JavaStaticField(isFinal: true)
  public var FRAME_DURATION_10000: Int32

  @JavaStaticField(isFinal: true)
  public var FRAME_DURATION_7500: Int32

  @JavaStaticField(isFinal: true)
  public var FRAME_DURATION_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var SAMPLE_RATE_11025: Int32

  @JavaStaticField(isFinal: true)
  public var SAMPLE_RATE_16000: Int32

  @JavaStaticField(isFinal: true)
  public var SAMPLE_RATE_176400: Int32

  @JavaStaticField(isFinal: true)
  public var SAMPLE_RATE_192000: Int32

  @JavaStaticField(isFinal: true)
  public var SAMPLE_RATE_22050: Int32

  @JavaStaticField(isFinal: true)
  public var SAMPLE_RATE_24000: Int32

  @JavaStaticField(isFinal: true)
  public var SAMPLE_RATE_32000: Int32

  @JavaStaticField(isFinal: true)
  public var SAMPLE_RATE_384000: Int32

  @JavaStaticField(isFinal: true)
  public var SAMPLE_RATE_44100: Int32

  @JavaStaticField(isFinal: true)
  public var SAMPLE_RATE_48000: Int32

  @JavaStaticField(isFinal: true)
  public var SAMPLE_RATE_8000: Int32

  @JavaStaticField(isFinal: true)
  public var SAMPLE_RATE_88200: Int32

  @JavaStaticField(isFinal: true)
  public var SAMPLE_RATE_96000: Int32

  @JavaStaticField(isFinal: true)
  public var SAMPLE_RATE_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var SOURCE_CODEC_TYPE_INVALID: Int32

  @JavaStaticField(isFinal: true)
  public var SOURCE_CODEC_TYPE_LC3: Int32

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
