// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import SwiftJava
import CSwiftJavaJNI
import JavaTime
import JavaUtil
import JavaLangUtil

/// Represents the local device Bluetooth adapter.
///
/// The `BluetoothAdapter` lets you perform fundamental Bluetooth tasks, such as initiate
/// device discovery, query a list of bonded (paired) devices, instantiate a `BluetoothDevice` using a known MAC address,
/// and create a `BluetoothServerSocket` to listen for connection requests from other devices, and start a scan for Bluetooth LE devices.
///
/// To get a `BluetoothAdapter` representing the local Bluetooth adapter, call the `BluetoothManager.getAdapter()` method on `BluetoothManager`.
/// On API level 17 and lower, use the static `getDefaultAdapter()` method.
///
/// - Since: API Level 5
@available(Android 5, *)
@JavaClass("android.bluetooth.BluetoothAdapter")
open class BluetoothAdapter: JavaObject {
  @JavaMethod
  open func getRemoteDevice(_ arg0: [Int8]) throws -> BluetoothDevice!

  @JavaMethod
  open func getRemoteDevice(_ arg0: String) throws -> BluetoothDevice!

  @JavaMethod
  open func getRemoteLeDevice(_ arg0: String, _ arg1: Int32) throws -> BluetoothDevice!

  @JavaMethod
  open func disable() -> Bool

  @JavaMethod
  open func getScanMode() -> Int32

  @JavaMethod
  open func startDiscovery() -> Bool

  @JavaMethod
  open func cancelDiscovery() -> Bool

  @JavaMethod
  open func isDiscovering() -> Bool

  /// Returns whether LE 2M PHY feature is supported.
  ///
  /// - Returns: `true` if chipset supports LE 2M PHY feature, `false` otherwise.
  /// - Since: API Level 26
  @available(Android 26, *)
  @JavaMethod
  open func isLe2MPhySupported() -> Bool

  /// Returns whether LE Audio is supported.
  ///
  /// - Returns: `FEATURE_SUPPORTED` if LE Audio is supported, `FEATURE_NOT_SUPPORTED` if not supported,
  ///   or an error code.
  /// - Since: API Level 33
  @available(Android 33, *)
  @JavaMethod
  open func isLeAudioSupported() -> Int32

  @JavaMethod
  open func getBondedDevices() -> JavaSet<BluetoothDevice>!

  @JavaMethod
  open func getProfileProxy(_ arg0: Context?, _ arg1: BluetoothProfile.ServiceListener?, _ arg2: Int32) -> Bool

  @JavaMethod
  open func closeProfileProxy(_ arg0: Int32, _ arg1: BluetoothProfile?)

  /// Starts a scan for Bluetooth LE devices, looking for devices that advertise given services.
  ///
  /// - Since: API Level 18
  /// - Deprecated: Use `BluetoothLeScanner.startScan()` instead (API 21+)
  @available(Android 18, deprecated: 21, message: "Use BluetoothLeScanner.startScan() instead")
  @JavaMethod
  open func startLeScan(_ arg0: [UUID?], _ arg1: BluetoothAdapter.LeScanCallback?) -> Bool

  /// Starts a scan for Bluetooth LE devices.
  ///
  /// - Since: API Level 18
  /// - Deprecated: Use `BluetoothLeScanner.startScan()` instead (API 21+)
  @available(Android 18, deprecated: 21, message: "Use BluetoothLeScanner.startScan() instead")
  @JavaMethod
  open func startLeScan(_ arg0: BluetoothAdapter.LeScanCallback?) -> Bool

  /// Stops an ongoing Bluetooth LE device scan.
  ///
  /// - Since: API Level 18
  /// - Deprecated: Use `BluetoothLeScanner.stopScan()` instead (API 21+)
  @available(Android 18, deprecated: 21, message: "Use BluetoothLeScanner.stopScan() instead")
  @JavaMethod
  open func stopLeScan(_ arg0: BluetoothAdapter.LeScanCallback?)

  /// Returns a `BluetoothLeAdvertiser` object for Bluetooth LE Advertising operations, or `nil` if Bluetooth LE Advertising is not supported on this adapter.
  ///
  /// - Returns: `BluetoothLeAdvertiser` instance, or `nil` if not supported.
  /// - Since: API Level 21
  @available(Android 21, *)
  @JavaMethod
  open func getBluetoothLeAdvertiser() -> BluetoothLeAdvertiser!

  /// Returns a `BluetoothLeScanner` object for Bluetooth LE scan operations.
  ///
  /// - Returns: `BluetoothLeScanner` instance.
  /// - Since: API Level 21
  @available(Android 21, *)
  @JavaMethod
  open func getBluetoothLeScanner() -> BluetoothLeScanner!

  /// Get the current discoverable timeout value.
  ///
  /// - Returns: the discoverable timeout value in seconds.
  /// - Since: API Level 33
  @available(Android 33, *)
  @JavaMethod
  open func getDiscoverableTimeout() -> Duration!

  @JavaMethod
  open func isMultipleAdvertisementSupported() -> Bool

  @JavaMethod
  open func isOffloadedFilteringSupported() -> Bool

  @JavaMethod
  open func isOffloadedScanBatchingSupported() -> Bool

  /// Returns whether LE Coded PHY feature is supported.
  ///
  /// - Returns: `true` if chipset supports LE Coded PHY feature, `false` otherwise.
  /// - Since: API Level 26
  @available(Android 26, *)
  @JavaMethod
  open func isLeCodedPhySupported() -> Bool

  /// Returns whether LE Extended Advertising feature is supported.
  ///
  /// - Returns: `true` if chipset supports LE Extended Advertising feature, `false` otherwise.
  /// - Since: API Level 26
  @available(Android 26, *)
  @JavaMethod
  open func isLeExtendedAdvertisingSupported() -> Bool

  /// Returns whether LE Periodic Advertising feature is supported.
  ///
  /// - Returns: `true` if chipset supports LE Periodic Advertising feature, `false` otherwise.
  /// - Since: API Level 26
  @available(Android 26, *)
  @JavaMethod
  open func isLePeriodicAdvertisingSupported() -> Bool

  /// Returns whether LE Audio Broadcast Source is supported.
  ///
  /// - Returns: `FEATURE_SUPPORTED` if supported, `FEATURE_NOT_SUPPORTED` if not supported,
  ///   or an error code.
  /// - Since: API Level 33
  @available(Android 33, *)
  @JavaMethod
  open func isLeAudioBroadcastSourceSupported() -> Int32

  /// Returns the maximum LE advertising data length in bytes, if LE Extended Advertising feature is supported.
  ///
  /// - Returns: the maximum LE advertising data length.
  /// - Since: API Level 26
  @available(Android 26, *)
  @JavaMethod
  open func getLeMaximumAdvertisingDataLength() -> Int32

  /// Returns the maximum number of connected audio devices.
  ///
  /// - Returns: the maximum number of connected audio devices.
  /// - Since: API Level 30
  @available(Android 30, *)
  @JavaMethod
  open func getMaxConnectedAudioDevices() -> Int32

  @JavaMethod
  open func getProfileConnectionState(_ arg0: Int32) -> Int32

  @JavaMethod
  open func listenUsingRfcommWithServiceRecord(_ arg0: String, _ arg1: UUID?) throws -> BluetoothServerSocket!

  /// Create a listening, secure L2CAP Connection-oriented Channel (CoC) `BluetoothServerSocket`.
  ///
  /// - Returns: a listening L2CAP CoC `BluetoothServerSocket`.
  /// - Throws: IOException on error, for example Bluetooth not available, or insufficient permissions.
  /// - Since: API Level 29
  @available(Android 29, *)
  @JavaMethod
  open func listenUsingL2capChannel() throws -> BluetoothServerSocket!

  /// Create a listening, insecure L2CAP Connection-oriented Channel (CoC) `BluetoothServerSocket`.
  ///
  /// - Returns: a listening L2CAP CoC `BluetoothServerSocket`.
  /// - Throws: IOException on error, for example Bluetooth not available, or insufficient permissions.
  /// - Since: API Level 29
  @available(Android 29, *)
  @JavaMethod
  open func listenUsingInsecureL2capChannel() throws -> BluetoothServerSocket!

  /// Returns whether LE Audio Broadcast Assistant is supported.
  ///
  /// - Returns: `FEATURE_SUPPORTED` if supported, `FEATURE_NOT_SUPPORTED` if not supported,
  ///   or an error code.
  /// - Since: API Level 33
  @available(Android 33, *)
  @JavaMethod
  open func isLeAudioBroadcastAssistantSupported() -> Int32

  @JavaMethod
  open func listenUsingInsecureRfcommWithServiceRecord(_ arg0: String, _ arg1: UUID?) throws -> BluetoothServerSocket!

  @JavaMethod
  open func getName() -> String

  @JavaMethod
  open override func finalize() throws

  @JavaMethod
  open func isEnabled() -> Bool

  @JavaMethod
  open func setName(_ arg0: String) -> Bool

  @JavaMethod
  open func getState() -> Int32

  @JavaMethod
  open func getAddress() -> String

  @JavaMethod
  open func enable() -> Bool
}
extension JavaClass<BluetoothAdapter> {
  @JavaStaticField(isFinal: true)
  public var ACTION_CONNECTION_STATE_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_DISCOVERY_FINISHED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_DISCOVERY_STARTED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_LOCAL_NAME_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_REQUEST_DISCOVERABLE: String

  @JavaStaticField(isFinal: true)
  public var ACTION_REQUEST_ENABLE: String

  @JavaStaticField(isFinal: true)
  public var ACTION_SCAN_MODE_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_STATE_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ERROR: Int32

  @JavaStaticField(isFinal: true)
  public var EXTRA_CONNECTION_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_DISCOVERABLE_DURATION: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_LOCAL_NAME: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PREVIOUS_CONNECTION_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PREVIOUS_SCAN_MODE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PREVIOUS_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_SCAN_MODE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_STATE: String

  @JavaStaticField(isFinal: true)
  public var SCAN_MODE_CONNECTABLE: Int32

  @JavaStaticField(isFinal: true)
  public var SCAN_MODE_CONNECTABLE_DISCOVERABLE: Int32

  @JavaStaticField(isFinal: true)
  public var SCAN_MODE_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CONNECTING: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_DISCONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_DISCONNECTING: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_OFF: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_ON: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_TURNING_OFF: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_TURNING_ON: Int32

  @JavaStaticMethod
  public func getDefaultAdapter() -> BluetoothAdapter!

  @JavaStaticMethod
  public func checkBluetoothAddress(_ arg0: String) -> Bool
}
