// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

extension BluetoothCodecStatus {
  @JavaClass("android.bluetooth.BluetoothCodecStatus$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func setCodecConfig(_ arg0: BluetoothCodecConfig?) -> BluetoothCodecStatus.Builder!

  @JavaMethod
  open func setCodecsLocalCapabilities(_ arg0: List<BluetoothCodecConfig>?) -> BluetoothCodecStatus.Builder!

  @JavaMethod
  open func setCodecsSelectableCapabilities(_ arg0: List<BluetoothCodecConfig>?) -> BluetoothCodecStatus.Builder!

  @JavaMethod
  open func build() -> BluetoothCodecStatus!
  }
}
