// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("android.bluetooth.BluetoothLeAudioCodecStatus", implements: Parcelable.self)
open class BluetoothLeAudioCodecStatus: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: BluetoothLeAudioCodecConfig?, _ arg1: BluetoothLeAudioCodecConfig?, _ arg2: List<BluetoothLeAudioCodecConfig>?, _ arg3: List<BluetoothLeAudioCodecConfig>?, _ arg4: List<BluetoothLeAudioCodecConfig>?, _ arg5: List<BluetoothLeAudioCodecConfig>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func isInputCodecConfigSelectable(_ arg0: BluetoothLeAudioCodecConfig?) -> Bool

  @JavaMethod
  open func isOutputCodecConfigSelectable(_ arg0: BluetoothLeAudioCodecConfig?) -> Bool

  @JavaMethod
  open func getInputCodecConfig() -> BluetoothLeAudioCodecConfig!

  @JavaMethod
  open func getOutputCodecConfig() -> BluetoothLeAudioCodecConfig!

  @JavaMethod
  open func getInputCodecLocalCapabilities() -> List<BluetoothLeAudioCodecConfig>!

  @JavaMethod
  open func getOutputCodecLocalCapabilities() -> List<BluetoothLeAudioCodecConfig>!

  @JavaMethod
  open func getInputCodecSelectableCapabilities() -> List<BluetoothLeAudioCodecConfig>!

  @JavaMethod
  open func getOutputCodecSelectableCapabilities() -> List<BluetoothLeAudioCodecConfig>!

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32
}
extension JavaClass<BluetoothLeAudioCodecStatus> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<BluetoothLeAudioCodecStatus>!

  @JavaStaticField(isFinal: true)
  public var EXTRA_LE_AUDIO_CODEC_STATUS: String

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
