// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import AndroidOS
import JavaKit
import JavaRuntime
import JavaUtil

@JavaClass("android.bluetooth.BluetoothDevice", implements: Parcelable.self)
open class BluetoothDevice: JavaObject {
  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func getAddressType() -> Int32

  @JavaMethod
  open func getAlias() -> String

  @JavaMethod
  open func setAlias(_ arg0: String) -> Int32

  @JavaMethod
  open func createBond() -> Bool

  @JavaMethod
  open func getBondState() -> Int32

  @JavaMethod
  open func getBluetoothClass() -> BluetoothClass!

  @JavaMethod
  open func getUuids() -> [ParcelUuid?]

  @JavaMethod
  open func fetchUuidsWithSdp() -> Bool

  @JavaMethod
  open func setPin(_ arg0: [Int8]) -> Bool

  @JavaMethod
  open func connectGatt(_ arg0: Context?, _ arg1: Bool, _ arg2: BluetoothGattCallback?) -> BluetoothGatt!

  @JavaMethod
  open func connectGatt(_ arg0: Context?, _ arg1: Bool, _ arg2: BluetoothGattCallback?, _ arg3: Int32) -> BluetoothGatt!

  @JavaMethod
  open func connectGatt(_ arg0: Context?, _ arg1: Bool, _ arg2: BluetoothGattCallback?, _ arg3: Int32, _ arg4: Int32) -> BluetoothGatt!

  @JavaMethod
  open func connectGatt(_ arg0: Context?, _ arg1: Bool, _ arg2: BluetoothGattCallback?, _ arg3: Int32, _ arg4: Int32, _ arg5: Handler?) -> BluetoothGatt!

  @JavaMethod
  open func createL2capChannel(_ arg0: Int32) throws -> BluetoothSocket!

  @JavaMethod
  open func setPairingConfirmation(_ arg0: Bool) -> Bool

  @JavaMethod
  open func createRfcommSocketToServiceRecord(_ arg0: UUID?) throws -> BluetoothSocket!

  @JavaMethod
  open func createInsecureL2capChannel(_ arg0: Int32) throws -> BluetoothSocket!

  @JavaMethod
  open func createInsecureRfcommSocketToServiceRecord(_ arg0: UUID?) throws -> BluetoothSocket!

  @JavaMethod
  open func getName() -> String

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func getType() -> Int32

  @JavaMethod
  open func getAddress() -> String
}
extension JavaClass<BluetoothDevice> {
  @JavaStaticField(isFinal: true)
  public var ACTION_ACL_CONNECTED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_ACL_DISCONNECTED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_ACL_DISCONNECT_REQUESTED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_ALIAS_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_BOND_STATE_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_CLASS_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_FOUND: String

  @JavaStaticField(isFinal: true)
  public var ACTION_NAME_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_PAIRING_REQUEST: String

  @JavaStaticField(isFinal: true)
  public var ACTION_UUID: String

  @JavaStaticField(isFinal: true)
  public var ADDRESS_TYPE_ANONYMOUS: Int32

  @JavaStaticField(isFinal: true)
  public var ADDRESS_TYPE_PUBLIC: Int32

  @JavaStaticField(isFinal: true)
  public var ADDRESS_TYPE_RANDOM: Int32

  @JavaStaticField(isFinal: true)
  public var ADDRESS_TYPE_UNKNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var BOND_BONDED: Int32

  @JavaStaticField(isFinal: true)
  public var BOND_BONDING: Int32

  @JavaStaticField(isFinal: true)
  public var BOND_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<BluetoothDevice>!

  @JavaStaticField(isFinal: true)
  public var DEVICE_TYPE_CLASSIC: Int32

  @JavaStaticField(isFinal: true)
  public var DEVICE_TYPE_DUAL: Int32

  @JavaStaticField(isFinal: true)
  public var DEVICE_TYPE_LE: Int32

  @JavaStaticField(isFinal: true)
  public var DEVICE_TYPE_UNKNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR: Int32

  @JavaStaticField(isFinal: true)
  public var EXTRA_BOND_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_CLASS: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_DEVICE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_IS_COORDINATED_SET_MEMBER: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_NAME: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PAIRING_KEY: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PAIRING_VARIANT: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PREVIOUS_BOND_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_RSSI: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_TRANSPORT: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_UUID: String

  @JavaStaticField(isFinal: true)
  public var PAIRING_VARIANT_PASSKEY_CONFIRMATION: Int32

  @JavaStaticField(isFinal: true)
  public var PAIRING_VARIANT_PIN: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_LE_1M: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_LE_1M_MASK: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_LE_2M: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_LE_2M_MASK: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_LE_CODED: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_LE_CODED_MASK: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_OPTION_NO_PREFERRED: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_OPTION_S2: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_OPTION_S8: Int32

  @JavaStaticField(isFinal: true)
  public var TRANSPORT_AUTO: Int32

  @JavaStaticField(isFinal: true)
  public var TRANSPORT_BREDR: Int32

  @JavaStaticField(isFinal: true)
  public var TRANSPORT_LE: Int32

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
