// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.BluetoothGattServerCallback")
open class BluetoothGattServerCallback: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func onServiceAdded(_ arg0: Int32, _ arg1: BluetoothGattService?)

  @JavaMethod
  open func onExecuteWrite(_ arg0: BluetoothDevice?, _ arg1: Int32, _ arg2: Bool)

  @JavaMethod
  open func onNotificationSent(_ arg0: BluetoothDevice?, _ arg1: Int32)

  @JavaMethod
  open func onMtuChanged(_ arg0: BluetoothDevice?, _ arg1: Int32)

  @JavaMethod
  open func onPhyUpdate(_ arg0: BluetoothDevice?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func onPhyRead(_ arg0: BluetoothDevice?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func onConnectionStateChange(_ arg0: BluetoothDevice?, _ arg1: Int32, _ arg2: Int32)

  @JavaMethod
  open func onCharacteristicReadRequest(_ arg0: BluetoothDevice?, _ arg1: Int32, _ arg2: Int32, _ arg3: BluetoothGattCharacteristic?)

  @JavaMethod
  open func onCharacteristicWriteRequest(_ arg0: BluetoothDevice?, _ arg1: Int32, _ arg2: BluetoothGattCharacteristic?, _ arg3: Bool, _ arg4: Bool, _ arg5: Int32, _ arg6: [Int8])

  @JavaMethod
  open func onDescriptorReadRequest(_ arg0: BluetoothDevice?, _ arg1: Int32, _ arg2: Int32, _ arg3: BluetoothGattDescriptor?)

  @JavaMethod
  open func onDescriptorWriteRequest(_ arg0: BluetoothDevice?, _ arg1: Int32, _ arg2: BluetoothGattDescriptor?, _ arg3: Bool, _ arg4: Bool, _ arg5: Int32, _ arg6: [Int8])
}
