// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.BluetoothHealthCallback")
open class BluetoothHealthCallback: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func onHealthChannelStateChange(_ arg0: BluetoothHealthAppConfiguration?, _ arg1: BluetoothDevice?, _ arg2: Int32, _ arg3: Int32, _ arg4: ParcelFileDescriptor?, _ arg5: Int32)

  @JavaMethod
  open func onHealthAppConfigurationStatusChange(_ arg0: BluetoothHealthAppConfiguration?, _ arg1: Int32)
}
