// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.BluetoothClass", implements: Parcelable.self)
open class BluetoothClass: JavaObject {
  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func hasService(_ arg0: Int32) -> Bool

  @JavaMethod
  open func getDeviceClass() -> Int32

  @JavaMethod
  open func doesClassMatch(_ arg0: Int32) -> Bool

  @JavaMethod
  open func getMajorDeviceClass() -> Int32

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32
}
extension JavaClass<BluetoothClass> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<BluetoothClass>!

  @JavaStaticField(isFinal: true)
  public var PROFILE_A2DP: Int32

  @JavaStaticField(isFinal: true)
  public var PROFILE_HEADSET: Int32

  @JavaStaticField(isFinal: true)
  public var PROFILE_HID: Int32

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
