// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("android.bluetooth.BluetoothGattCallback")
open class BluetoothGattCallback: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func onMtuChanged(_ arg0: BluetoothGatt?, _ arg1: Int32, _ arg2: Int32)

  @JavaMethod
  open func onPhyUpdate(_ arg0: BluetoothGatt?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func onPhyRead(_ arg0: BluetoothGatt?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func onDescriptorRead(_ arg0: BluetoothGatt?, _ arg1: BluetoothGattDescriptor?, _ arg2: Int32)

  @JavaMethod
  open func onDescriptorRead(_ arg0: BluetoothGatt?, _ arg1: BluetoothGattDescriptor?, _ arg2: Int32, _ arg3: [Int8])

  @JavaMethod
  open func onDescriptorWrite(_ arg0: BluetoothGatt?, _ arg1: BluetoothGattDescriptor?, _ arg2: Int32)

  @JavaMethod
  open func onReadRemoteRssi(_ arg0: BluetoothGatt?, _ arg1: Int32, _ arg2: Int32)

  @JavaMethod
  open func onServiceChanged(_ arg0: BluetoothGatt?)

  @JavaMethod
  open func onConnectionStateChange(_ arg0: BluetoothGatt?, _ arg1: Int32, _ arg2: Int32)

  @JavaMethod
  open func onServicesDiscovered(_ arg0: BluetoothGatt?, _ arg1: Int32)

  @JavaMethod
  open func onCharacteristicRead(_ arg0: BluetoothGatt?, _ arg1: BluetoothGattCharacteristic?, _ arg2: [Int8], _ arg3: Int32)

  @JavaMethod
  open func onCharacteristicRead(_ arg0: BluetoothGatt?, _ arg1: BluetoothGattCharacteristic?, _ arg2: Int32)

  @JavaMethod
  open func onCharacteristicWrite(_ arg0: BluetoothGatt?, _ arg1: BluetoothGattCharacteristic?, _ arg2: Int32)

  @JavaMethod
  open func onCharacteristicChanged(_ arg0: BluetoothGatt?, _ arg1: BluetoothGattCharacteristic?)

  @JavaMethod
  open func onCharacteristicChanged(_ arg0: BluetoothGatt?, _ arg1: BluetoothGattCharacteristic?, _ arg2: [Int8])

  @JavaMethod
  open func onReliableWriteCompleted(_ arg0: BluetoothGatt?, _ arg1: Int32)
}
