// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension BluetoothClass {
  @JavaClass("android.bluetooth.BluetoothClass$Service")
  open class Service: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
  }
}
extension JavaClass<BluetoothClass.Service> {
  @JavaStaticField(isFinal: true)
  public var AUDIO: Int32

  @JavaStaticField(isFinal: true)
  public var CAPTURE: Int32

  @JavaStaticField(isFinal: true)
  public var INFORMATION: Int32

  @JavaStaticField(isFinal: true)
  public var LE_AUDIO: Int32

  @JavaStaticField(isFinal: true)
  public var LIMITED_DISCOVERABILITY: Int32

  @JavaStaticField(isFinal: true)
  public var NETWORKING: Int32

  @JavaStaticField(isFinal: true)
  public var OBJECT_TRANSFER: Int32

  @JavaStaticField(isFinal: true)
  public var POSITIONING: Int32

  @JavaStaticField(isFinal: true)
  public var RENDER: Int32

  @JavaStaticField(isFinal: true)
  public var TELEPHONY: Int32
}
