// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.BluetoothServerSocket", implements: Closeable.self)
open class BluetoothServerSocket: JavaObject {
  @JavaMethod
  open func getPsm() -> Int32

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open func accept(_ arg0: Int32) throws -> BluetoothSocket!

  @JavaMethod
  open func accept() throws -> BluetoothSocket!

  @JavaMethod
  open func close() throws
}
