// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import SwiftJava
import CSwiftJavaJNI

/// High level manager used to obtain an instance of a `BluetoothAdapter` and to conduct overall Bluetooth Management.
///
/// Use `Context.getSystemService(Context.BLUETOOTH_SERVICE)` to create a `BluetoothManager`, then call `getAdapter()` to obtain the `BluetoothAdapter`.
///
/// - Since: API Level 18
@available(Android 18, *)
@JavaClass("android.bluetooth.BluetoothManager")
open class BluetoothManager: JavaObject {
  @JavaMethod
  open func getConnectionState(_ arg0: BluetoothDevice?, _ arg1: Int32) -> Int32

  @JavaMethod
  open func openGattServer(_ arg0: Context?, _ arg1: BluetoothGattServerCallback?) -> BluetoothGattServer!

  @JavaMethod
  open func getConnectedDevices(_ arg0: Int32) -> List<BluetoothDevice>!

  @JavaMethod
  open func getDevicesMatchingConnectionStates(_ arg0: Int32, _ arg1: [Int32]) -> List<BluetoothDevice>!

  @JavaMethod
  open func getAdapter() -> BluetoothAdapter!
}
