// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI
import JavaUtil
import JavaLangUtil

@JavaClass("android.bluetooth.BluetoothGattServer", implements: BluetoothProfile.self)
open class BluetoothGattServer: JavaObject {
  @JavaMethod
  open func getConnectionState(_ arg0: BluetoothDevice?) -> Int32

  @JavaMethod
  open func connect(_ arg0: BluetoothDevice?, _ arg1: Bool) -> Bool

  @JavaMethod
  open func setPreferredPhy(_ arg0: BluetoothDevice?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func readPhy(_ arg0: BluetoothDevice?)

  @JavaMethod
  open func getServices() -> List<BluetoothGattService>!

  @JavaMethod
  open func getService(_ arg0: UUID?) -> BluetoothGattService!

  @JavaMethod
  open func addService(_ arg0: BluetoothGattService?) -> Bool

  @JavaMethod
  open func cancelConnection(_ arg0: BluetoothDevice?)

  @JavaMethod
  open func sendResponse(_ arg0: BluetoothDevice?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: [Int8]) -> Bool

  @JavaMethod
  open func removeService(_ arg0: BluetoothGattService?) -> Bool

  @JavaMethod
  open func clearServices()

  @JavaMethod
  open func getConnectedDevices() -> List<BluetoothDevice>!

  @JavaMethod
  open func getDevicesMatchingConnectionStates(_ arg0: [Int32]) -> List<BluetoothDevice>!

  @JavaMethod
  open func notifyCharacteristicChanged(_ arg0: BluetoothDevice?, _ arg1: BluetoothGattCharacteristic?, _ arg2: Bool, _ arg3: [Int8]) -> Int32

  @JavaMethod
  open func notifyCharacteristicChanged(_ arg0: BluetoothDevice?, _ arg1: BluetoothGattCharacteristic?, _ arg2: Bool) -> Bool

  @JavaMethod
  open func close()
}
extension JavaClass<BluetoothGattServer> {
  @JavaStaticField(isFinal: true)
  public var A2DP: Int32

  @JavaStaticField(isFinal: true)
  public var CSIP_SET_COORDINATOR: Int32

  @JavaStaticField(isFinal: true)
  public var EXTRA_PREVIOUS_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_STATE: String

  @JavaStaticField(isFinal: true)
  public var GATT: Int32

  @JavaStaticField(isFinal: true)
  public var GATT_SERVER: Int32

  @JavaStaticField(isFinal: true)
  public var HAP_CLIENT: Int32

  @JavaStaticField(isFinal: true)
  public var HEADSET: Int32

  @JavaStaticField(isFinal: true)
  public var HEALTH: Int32

  @JavaStaticField(isFinal: true)
  public var HEARING_AID: Int32

  @JavaStaticField(isFinal: true)
  public var HID_DEVICE: Int32

  @JavaStaticField(isFinal: true)
  public var LE_AUDIO: Int32

  @JavaStaticField(isFinal: true)
  public var SAP: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CONNECTING: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_DISCONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_DISCONNECTING: Int32
}
