// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("android.bluetooth.BluetoothAssignedNumbers")
open class BluetoothAssignedNumbers: JavaObject {

}

#if DEBUG
extension JavaClass<BluetoothAssignedNumbers> {
  @JavaStaticField(isFinal: true)
  public var AAMP_OF_AMERICA: Int32

  @JavaStaticField(isFinal: true)
  public var ACCEL_SEMICONDUCTOR: Int32

  @JavaStaticField(isFinal: true)
  public var ACE_SENSOR: Int32

  @JavaStaticField(isFinal: true)
  public var ADIDAS: Int32

  @JavaStaticField(isFinal: true)
  public var ADVANCED_PANMOBIL_SYSTEMS: Int32

  @JavaStaticField(isFinal: true)
  public var AIROHA_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var ALCATEL: Int32

  @JavaStaticField(isFinal: true)
  public var ALPWISE: Int32

  @JavaStaticField(isFinal: true)
  public var AMICCOM_ELECTRONICS: Int32

  @JavaStaticField(isFinal: true)
  public var APLIX: Int32

  @JavaStaticField(isFinal: true)
  public var APPLE: Int32

  @JavaStaticField(isFinal: true)
  public var APT_LICENSING: Int32

  @JavaStaticField(isFinal: true)
  public var ARCHOS: Int32

  @JavaStaticField(isFinal: true)
  public var ARP_DEVICES: Int32

  @JavaStaticField(isFinal: true)
  public var ATHEROS_COMMUNICATIONS: Int32

  @JavaStaticField(isFinal: true)
  public var ATMEL: Int32

  @JavaStaticField(isFinal: true)
  public var AUSTCO_COMMUNICATION_SYSTEMS: Int32

  @JavaStaticField(isFinal: true)
  public var AUTONET_MOBILE: Int32

  @JavaStaticField(isFinal: true)
  public var AVAGO: Int32

  @JavaStaticField(isFinal: true)
  public var AVM_BERLIN: Int32

  @JavaStaticField(isFinal: true)
  public var A_AND_D_ENGINEERING: Int32

  @JavaStaticField(isFinal: true)
  public var A_AND_R_CAMBRIDGE: Int32

  @JavaStaticField(isFinal: true)
  public var BANDSPEED: Int32

  @JavaStaticField(isFinal: true)
  public var BAND_XI_INTERNATIONAL: Int32

  @JavaStaticField(isFinal: true)
  public var BDE_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var BEATS_ELECTRONICS: Int32

  @JavaStaticField(isFinal: true)
  public var BEAUTIFUL_ENTERPRISE: Int32

  @JavaStaticField(isFinal: true)
  public var BEKEY: Int32

  @JavaStaticField(isFinal: true)
  public var BELKIN_INTERNATIONAL: Int32

  @JavaStaticField(isFinal: true)
  public var BINAURIC: Int32

  @JavaStaticField(isFinal: true)
  public var BIOSENTRONICS: Int32

  @JavaStaticField(isFinal: true)
  public var BLUEGIGA: Int32

  @JavaStaticField(isFinal: true)
  public var BLUERADIOS: Int32

  @JavaStaticField(isFinal: true)
  public var BLUETOOTH_SIG: Int32

  @JavaStaticField(isFinal: true)
  public var BLUETREK_TECHNOLOGIES: Int32

  @JavaStaticField(isFinal: true)
  public var BOSE: Int32

  @JavaStaticField(isFinal: true)
  public var BRIARTEK: Int32

  @JavaStaticField(isFinal: true)
  public var BROADCOM: Int32

  @JavaStaticField(isFinal: true)
  public var CAEN_RFID: Int32

  @JavaStaticField(isFinal: true)
  public var CAMBRIDGE_SILICON_RADIO: Int32

  @JavaStaticField(isFinal: true)
  public var CATC: Int32

  @JavaStaticField(isFinal: true)
  public var CINETIX: Int32

  @JavaStaticField(isFinal: true)
  public var CLARINOX_TECHNOLOGIES: Int32

  @JavaStaticField(isFinal: true)
  public var COLORFY: Int32

  @JavaStaticField(isFinal: true)
  public var COMMIL: Int32

  @JavaStaticField(isFinal: true)
  public var CONEXANT_SYSTEMS: Int32

  @JavaStaticField(isFinal: true)
  public var CONNECTBLUE: Int32

  @JavaStaticField(isFinal: true)
  public var CONTINENTAL_AUTOMOTIVE: Int32

  @JavaStaticField(isFinal: true)
  public var CONWISE_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var CREATIVE_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var C_TECHNOLOGIES: Int32

  @JavaStaticField(isFinal: true)
  public var DANLERS: Int32

  @JavaStaticField(isFinal: true)
  public var DELORME_PUBLISHING_COMPANY: Int32

  @JavaStaticField(isFinal: true)
  public var DEXCOM: Int32

  @JavaStaticField(isFinal: true)
  public var DIALOG_SEMICONDUCTOR: Int32

  @JavaStaticField(isFinal: true)
  public var DIGIANSWER: Int32

  @JavaStaticField(isFinal: true)
  public var ECLIPSE: Int32

  @JavaStaticField(isFinal: true)
  public var ECOTEST: Int32

  @JavaStaticField(isFinal: true)
  public var ELGATO_SYSTEMS: Int32

  @JavaStaticField(isFinal: true)
  public var EM_MICROELECTRONIC_MARIN: Int32

  @JavaStaticField(isFinal: true)
  public var EQUINOX_AG: Int32

  @JavaStaticField(isFinal: true)
  public var ERICSSON_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var EVLUMA: Int32

  @JavaStaticField(isFinal: true)
  public var FREE2MOVE: Int32

  @JavaStaticField(isFinal: true)
  public var FUNAI_ELECTRIC: Int32

  @JavaStaticField(isFinal: true)
  public var GARMIN_INTERNATIONAL: Int32

  @JavaStaticField(isFinal: true)
  public var GCT_SEMICONDUCTOR: Int32

  @JavaStaticField(isFinal: true)
  public var GELO: Int32

  @JavaStaticField(isFinal: true)
  public var GENEQ: Int32

  @JavaStaticField(isFinal: true)
  public var GENERAL_MOTORS: Int32

  @JavaStaticField(isFinal: true)
  public var GENNUM: Int32

  @JavaStaticField(isFinal: true)
  public var GEOFORCE: Int32

  @JavaStaticField(isFinal: true)
  public var GIBSON_GUITARS: Int32

  @JavaStaticField(isFinal: true)
  public var GN_NETCOM: Int32

  @JavaStaticField(isFinal: true)
  public var GN_RESOUND: Int32

  @JavaStaticField(isFinal: true)
  public var GOOGLE: Int32

  @JavaStaticField(isFinal: true)
  public var GREEN_THROTTLE_GAMES: Int32

  @JavaStaticField(isFinal: true)
  public var GROUP_SENSE: Int32

  @JavaStaticField(isFinal: true)
  public var HANLYNN_TECHNOLOGIES: Int32

  @JavaStaticField(isFinal: true)
  public var HARMAN_INTERNATIONAL: Int32

  @JavaStaticField(isFinal: true)
  public var HEWLETT_PACKARD: Int32

  @JavaStaticField(isFinal: true)
  public var HITACHI: Int32

  @JavaStaticField(isFinal: true)
  public var HOSIDEN: Int32

  @JavaStaticField(isFinal: true)
  public var IBM: Int32

  @JavaStaticField(isFinal: true)
  public var INFINEON_TECHNOLOGIES: Int32

  @JavaStaticField(isFinal: true)
  public var INGENIEUR_SYSTEMGRUPPE_ZAHN: Int32

  @JavaStaticField(isFinal: true)
  public var INTEGRATED_SILICON_SOLUTION: Int32

  @JavaStaticField(isFinal: true)
  public var INTEGRATED_SYSTEM_SOLUTION: Int32

  @JavaStaticField(isFinal: true)
  public var INTEL: Int32

  @JavaStaticField(isFinal: true)
  public var INVENTEL: Int32

  @JavaStaticField(isFinal: true)
  public var IPEXTREME: Int32

  @JavaStaticField(isFinal: true)
  public var I_TECH_DYNAMIC_GLOBAL_DISTRIBUTION: Int32

  @JavaStaticField(isFinal: true)
  public var JAWBONE: Int32

  @JavaStaticField(isFinal: true)
  public var JIANGSU_TOPPOWER_AUTOMOTIVE_ELECTRONICS: Int32

  @JavaStaticField(isFinal: true)
  public var JOHNSON_CONTROLS: Int32

  @JavaStaticField(isFinal: true)
  public var J_AND_M: Int32

  @JavaStaticField(isFinal: true)
  public var KAWANTECH: Int32

  @JavaStaticField(isFinal: true)
  public var KC_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var KENSINGTON_COMPUTER_PRODUCTS_GROUP: Int32

  @JavaStaticField(isFinal: true)
  public var LAIRD_TECHNOLOGIES: Int32

  @JavaStaticField(isFinal: true)
  public var LESSWIRE: Int32

  @JavaStaticField(isFinal: true)
  public var LG_ELECTRONICS: Int32

  @JavaStaticField(isFinal: true)
  public var LINAK: Int32

  @JavaStaticField(isFinal: true)
  public var LUCENT: Int32

  @JavaStaticField(isFinal: true)
  public var LUDUS_HELSINKI: Int32

  @JavaStaticField(isFinal: true)
  public var MACRONIX: Int32

  @JavaStaticField(isFinal: true)
  public var MAGNETI_MARELLI: Int32

  @JavaStaticField(isFinal: true)
  public var MANSELLA: Int32

  @JavaStaticField(isFinal: true)
  public var MARVELL: Int32

  @JavaStaticField(isFinal: true)
  public var MATSUSHITA_ELECTRIC: Int32

  @JavaStaticField(isFinal: true)
  public var MC10: Int32

  @JavaStaticField(isFinal: true)
  public var MEDIATEK: Int32

  @JavaStaticField(isFinal: true)
  public var MESO_INTERNATIONAL: Int32

  @JavaStaticField(isFinal: true)
  public var META_WATCH: Int32

  @JavaStaticField(isFinal: true)
  public var MEWTEL_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var MICOMMAND: Int32

  @JavaStaticField(isFinal: true)
  public var MICROCHIP_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var MICROSOFT: Int32

  @JavaStaticField(isFinal: true)
  public var MINDTREE: Int32

  @JavaStaticField(isFinal: true)
  public var MISFIT_WEARABLES: Int32

  @JavaStaticField(isFinal: true)
  public var MITEL_SEMICONDUCTOR: Int32

  @JavaStaticField(isFinal: true)
  public var MITSUBISHI_ELECTRIC: Int32

  @JavaStaticField(isFinal: true)
  public var MOBILIAN_CORPORATION: Int32

  @JavaStaticField(isFinal: true)
  public var MONSTER: Int32

  @JavaStaticField(isFinal: true)
  public var MOTOROLA: Int32

  @JavaStaticField(isFinal: true)
  public var MSTAR_SEMICONDUCTOR: Int32

  @JavaStaticField(isFinal: true)
  public var MUZIK: Int32

  @JavaStaticField(isFinal: true)
  public var NEC: Int32

  @JavaStaticField(isFinal: true)
  public var NEC_LIGHTING: Int32

  @JavaStaticField(isFinal: true)
  public var NEWLOGIC: Int32

  @JavaStaticField(isFinal: true)
  public var NIKE: Int32

  @JavaStaticField(isFinal: true)
  public var NINE_SOLUTIONS: Int32

  @JavaStaticField(isFinal: true)
  public var NOKIA_MOBILE_PHONES: Int32

  @JavaStaticField(isFinal: true)
  public var NORDIC_SEMICONDUCTOR: Int32

  @JavaStaticField(isFinal: true)
  public var NORWOOD_SYSTEMS: Int32

  @JavaStaticField(isFinal: true)
  public var ODM_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var OMEGAWAVE: Int32

  @JavaStaticField(isFinal: true)
  public var ONSET_COMPUTER: Int32

  @JavaStaticField(isFinal: true)
  public var OPEN_INTERFACE: Int32

  @JavaStaticField(isFinal: true)
  public var OTL_DYNAMICS: Int32

  @JavaStaticField(isFinal: true)
  public var PANDA_OCEAN: Int32

  @JavaStaticField(isFinal: true)
  public var PARROT: Int32

  @JavaStaticField(isFinal: true)
  public var PARTHUS_TECHNOLOGIES: Int32

  @JavaStaticField(isFinal: true)
  public var PASSIF_SEMICONDUCTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PETER_SYSTEMTECHNIK: Int32

  @JavaStaticField(isFinal: true)
  public var PHILIPS_SEMICONDUCTORS: Int32

  @JavaStaticField(isFinal: true)
  public var PLANTRONICS: Int32

  @JavaStaticField(isFinal: true)
  public var POLAR_ELECTRO: Int32

  @JavaStaticField(isFinal: true)
  public var POLAR_ELECTRO_EUROPE: Int32

  @JavaStaticField(isFinal: true)
  public var PROCTER_AND_GAMBLE: Int32

  @JavaStaticField(isFinal: true)
  public var QUALCOMM: Int32

  @JavaStaticField(isFinal: true)
  public var QUALCOMM_CONNECTED_EXPERIENCES: Int32

  @JavaStaticField(isFinal: true)
  public var QUALCOMM_INNOVATION_CENTER: Int32

  @JavaStaticField(isFinal: true)
  public var QUALCOMM_LABS: Int32

  @JavaStaticField(isFinal: true)
  public var QUALCOMM_TECHNOLOGIES: Int32

  @JavaStaticField(isFinal: true)
  public var QUINTIC: Int32

  @JavaStaticField(isFinal: true)
  public var QUUPPA: Int32

  @JavaStaticField(isFinal: true)
  public var RALINK_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var RDA_MICROELECTRONICS: Int32

  @JavaStaticField(isFinal: true)
  public var REALTEK_SEMICONDUCTOR: Int32

  @JavaStaticField(isFinal: true)
  public var RED_M: Int32

  @JavaStaticField(isFinal: true)
  public var RENESAS_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var RESEARCH_IN_MOTION: Int32

  @JavaStaticField(isFinal: true)
  public var RF_MICRO_DEVICES: Int32

  @JavaStaticField(isFinal: true)
  public var RIVIERAWAVES: Int32

  @JavaStaticField(isFinal: true)
  public var ROHDE_AND_SCHWARZ: Int32

  @JavaStaticField(isFinal: true)
  public var RTX_TELECOM: Int32

  @JavaStaticField(isFinal: true)
  public var SAMSUNG_ELECTRONICS: Int32

  @JavaStaticField(isFinal: true)
  public var SARIS_CYCLING_GROUP: Int32

  @JavaStaticField(isFinal: true)
  public var SEERS_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var SEIKO_EPSON: Int32

  @JavaStaticField(isFinal: true)
  public var SELFLY: Int32

  @JavaStaticField(isFinal: true)
  public var SEMILINK: Int32

  @JavaStaticField(isFinal: true)
  public var SENNHEISER_COMMUNICATIONS: Int32

  @JavaStaticField(isFinal: true)
  public var SHANGHAI_SUPER_SMART_ELECTRONICS: Int32

  @JavaStaticField(isFinal: true)
  public var SHENZHEN_EXCELSECU_DATA_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var SIGNIA_TECHNOLOGIES: Int32

  @JavaStaticField(isFinal: true)
  public var SILICON_WAVE: Int32

  @JavaStaticField(isFinal: true)
  public var SIRF_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var SOCKET_MOBILE: Int32

  @JavaStaticField(isFinal: true)
  public var SONY_ERICSSON: Int32

  @JavaStaticField(isFinal: true)
  public var SOUND_ID: Int32

  @JavaStaticField(isFinal: true)
  public var SPORTS_TRACKING_TECHNOLOGIES: Int32

  @JavaStaticField(isFinal: true)
  public var SR_MEDIZINELEKTRONIK: Int32

  @JavaStaticField(isFinal: true)
  public var STACCATO_COMMUNICATIONS: Int32

  @JavaStaticField(isFinal: true)
  public var STALMART_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var STARKEY_LABORATORIES: Int32

  @JavaStaticField(isFinal: true)
  public var STOLLMAN_E_PLUS_V: Int32

  @JavaStaticField(isFinal: true)
  public var STONESTREET_ONE: Int32

  @JavaStaticField(isFinal: true)
  public var ST_MICROELECTRONICS: Int32

  @JavaStaticField(isFinal: true)
  public var SUMMIT_DATA_COMMUNICATIONS: Int32

  @JavaStaticField(isFinal: true)
  public var SUUNTO: Int32

  @JavaStaticField(isFinal: true)
  public var SWIRL_NETWORKS: Int32

  @JavaStaticField(isFinal: true)
  public var SYMBOL_TECHNOLOGIES: Int32

  @JavaStaticField(isFinal: true)
  public var SYNOPSYS: Int32

  @JavaStaticField(isFinal: true)
  public var SYSTEMS_AND_CHIPS: Int32

  @JavaStaticField(isFinal: true)
  public var S_POWER_ELECTRONICS: Int32

  @JavaStaticField(isFinal: true)
  public var TAIXINGBANG_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var TENOVIS: Int32

  @JavaStaticField(isFinal: true)
  public var TERAX: Int32

  @JavaStaticField(isFinal: true)
  public var TEXAS_INSTRUMENTS: Int32

  @JavaStaticField(isFinal: true)
  public var THINKOPTICS: Int32

  @JavaStaticField(isFinal: true)
  public var THREECOM: Int32

  @JavaStaticField(isFinal: true)
  public var THREE_DIJOY: Int32

  @JavaStaticField(isFinal: true)
  public var THREE_DSP: Int32

  @JavaStaticField(isFinal: true)
  public var TIMEKEEPING_SYSTEMS: Int32

  @JavaStaticField(isFinal: true)
  public var TIMEX_GROUP_USA: Int32

  @JavaStaticField(isFinal: true)
  public var TOPCORN_POSITIONING_SYSTEMS: Int32

  @JavaStaticField(isFinal: true)
  public var TOSHIBA: Int32

  @JavaStaticField(isFinal: true)
  public var TRANSILICA: Int32

  @JavaStaticField(isFinal: true)
  public var TRELAB: Int32

  @JavaStaticField(isFinal: true)
  public var TTPCOM: Int32

  @JavaStaticField(isFinal: true)
  public var TXTR: Int32

  @JavaStaticField(isFinal: true)
  public var TZERO_TECHNOLOGIES: Int32

  @JavaStaticField(isFinal: true)
  public var UNIVERSAL_ELECTRONICS: Int32

  @JavaStaticField(isFinal: true)
  public var VERTU: Int32

  @JavaStaticField(isFinal: true)
  public var VISTEON: Int32

  @JavaStaticField(isFinal: true)
  public var VIZIO: Int32

  @JavaStaticField(isFinal: true)
  public var VOYETRA_TURTLE_BEACH: Int32

  @JavaStaticField(isFinal: true)
  public var WAVEPLUS_TECHNOLOGY: Int32

  @JavaStaticField(isFinal: true)
  public var WICENTRIC: Int32

  @JavaStaticField(isFinal: true)
  public var WIDCOMM: Int32

  @JavaStaticField(isFinal: true)
  public var WUXI_VIMICRO: Int32

  @JavaStaticField(isFinal: true)
  public var ZEEVO: Int32

  @JavaStaticField(isFinal: true)
  public var ZER01_TV: Int32

  @JavaStaticField(isFinal: true)
  public var ZOMM: Int32

  @JavaStaticField(isFinal: true)
  public var ZSCAN_SOFTWARE: Int32
}
#endif
