// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaKit
import JavaRuntime

@JavaClass("android.bluetooth.le.BluetoothLeAdvertiser")
open class BluetoothLeAdvertiser: JavaObject {
  @JavaMethod
  open func startAdvertising(_ arg0: AdvertiseSettings?, _ arg1: AdvertiseData?, _ arg2: AdvertiseData?, _ arg3: AdvertiseCallback?)

  @JavaMethod
  open func startAdvertising(_ arg0: AdvertiseSettings?, _ arg1: AdvertiseData?, _ arg2: AdvertiseCallback?)

  @JavaMethod
  open func stopAdvertising(_ arg0: AdvertiseCallback?)

  @JavaMethod
  open func stopAdvertisingSet(_ arg0: AdvertisingSetCallback?)

  @JavaMethod
  open func startAdvertisingSet(_ arg0: AdvertisingSetParameters?, _ arg1: AdvertiseData?, _ arg2: AdvertiseData?, _ arg3: PeriodicAdvertisingParameters?, _ arg4: AdvertiseData?, _ arg5: Int32, _ arg6: Int32, _ arg7: AdvertisingSetCallback?, _ arg8: Handler?)

  @JavaMethod
  open func startAdvertisingSet(_ arg0: AdvertisingSetParameters?, _ arg1: AdvertiseData?, _ arg2: AdvertiseData?, _ arg3: PeriodicAdvertisingParameters?, _ arg4: AdvertiseData?, _ arg5: Int32, _ arg6: Int32, _ arg7: AdvertisingSetCallback?)

  @JavaMethod
  open func startAdvertisingSet(_ arg0: AdvertisingSetParameters?, _ arg1: AdvertiseData?, _ arg2: AdvertiseData?, _ arg3: PeriodicAdvertisingParameters?, _ arg4: AdvertiseData?, _ arg5: AdvertisingSetCallback?, _ arg6: Handler?)

  @JavaMethod
  open func startAdvertisingSet(_ arg0: AdvertisingSetParameters?, _ arg1: AdvertiseData?, _ arg2: AdvertiseData?, _ arg3: PeriodicAdvertisingParameters?, _ arg4: AdvertiseData?, _ arg5: AdvertisingSetCallback?)
}
