// Auto-generated by Java-to-Swift wrapper generator.
import AndroidApp
import SwiftJava
import CSwiftJavaJNI

/// This class provides methods to perform scan related operations for Bluetooth LE devices.
///
/// An application can scan for a particular type of Bluetooth LE devices using `ScanFilter`.
/// It can also request different types of callbacks for delivering the result.
///
/// Use `BluetoothAdapter.getBluetoothLeScanner()` to get an instance of `BluetoothLeScanner`.
///
/// - Since: API Level 21
@available(Android 21, *)
@JavaClass("android.bluetooth.le.BluetoothLeScanner")
open class BluetoothLeScanner: JavaObject {
  @JavaMethod
  open func startScan(_ arg0: List<ScanFilter>?, _ arg1: ScanSettings?, _ arg2: ScanCallback?) throws

  @JavaMethod
  open func startScan(_ arg0: ScanCallback?) throws

  @JavaMethod
  open func startScan(_ arg0: List<ScanFilter>?, _ arg1: ScanSettings?, _ arg2: PendingIntent?) -> Int32

  @JavaMethod
  open func stopScan(_ arg0: PendingIntent?)

  @JavaMethod
  open func stopScan(_ arg0: ScanCallback?)

  @JavaMethod
  open func flushPendingScanResults(_ arg0: ScanCallback?)
}
extension JavaClass<BluetoothLeScanner> {
  @JavaStaticField(isFinal: true)
  public var EXTRA_CALLBACK_TYPE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_ERROR_CODE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_LIST_SCAN_RESULT: String
}
