// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension BluetoothLeAudioCodecConfig {
  @JavaClass("android.bluetooth.BluetoothLeAudioCodecConfig$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: BluetoothLeAudioCodecConfig?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func setCodecType(_ arg0: Int32) -> BluetoothLeAudioCodecConfig.Builder!

  @JavaMethod
  open func setCodecPriority(_ arg0: Int32) -> BluetoothLeAudioCodecConfig.Builder!

  @JavaMethod
  open func setSampleRate(_ arg0: Int32) -> BluetoothLeAudioCodecConfig.Builder!

  @JavaMethod
  open func setBitsPerSample(_ arg0: Int32) -> BluetoothLeAudioCodecConfig.Builder!

  @JavaMethod
  open func setChannelCount(_ arg0: Int32) -> BluetoothLeAudioCodecConfig.Builder!

  @JavaMethod
  open func setFrameDuration(_ arg0: Int32) -> BluetoothLeAudioCodecConfig.Builder!

  @JavaMethod
  open func setOctetsPerFrame(_ arg0: Int32) -> BluetoothLeAudioCodecConfig.Builder!

  @JavaMethod
  open func setMinOctetsPerFrame(_ arg0: Int32) -> BluetoothLeAudioCodecConfig.Builder!

  @JavaMethod
  open func setMaxOctetsPerFrame(_ arg0: Int32) -> BluetoothLeAudioCodecConfig.Builder!

  @JavaMethod
  open func build() -> BluetoothLeAudioCodecConfig!
  }
}
