// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.BluetoothA2dp", implements: BluetoothProfile.self)
open class BluetoothA2dp: JavaObject {
  @JavaMethod
  open func getConnectionState(_ arg0: BluetoothDevice?) -> Int32

  @JavaMethod
  open func isA2dpPlaying(_ arg0: BluetoothDevice?) -> Bool

  @JavaMethod
  open func getConnectedDevices() -> List<BluetoothDevice>!

  @JavaMethod
  open func getDevicesMatchingConnectionStates(_ arg0: [Int32]) -> List<BluetoothDevice>!

  @JavaMethod
  open func getSupportedCodecTypes() -> JavaCollection<BluetoothCodecType>!

  @JavaMethod
  open override func finalize()
}
extension JavaClass<BluetoothA2dp> {
  @JavaStaticField(isFinal: true)
  public var ACTION_CONNECTION_STATE_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_PLAYING_STATE_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var STATE_NOT_PLAYING: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_PLAYING: Int32

  @JavaStaticField(isFinal: true)
  public var A2DP: Int32

  @JavaStaticField(isFinal: true)
  public var CSIP_SET_COORDINATOR: Int32

  @JavaStaticField(isFinal: true)
  public var EXTRA_PREVIOUS_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_STATE: String

  @JavaStaticField(isFinal: true)
  public var GATT: Int32

  @JavaStaticField(isFinal: true)
  public var GATT_SERVER: Int32

  @JavaStaticField(isFinal: true)
  public var HAP_CLIENT: Int32

  @JavaStaticField(isFinal: true)
  public var HEADSET: Int32

  @JavaStaticField(isFinal: true)
  public var HEALTH: Int32

  @JavaStaticField(isFinal: true)
  public var HEARING_AID: Int32

  @JavaStaticField(isFinal: true)
  public var HID_DEVICE: Int32

  @JavaStaticField(isFinal: true)
  public var LE_AUDIO: Int32

  @JavaStaticField(isFinal: true)
  public var SAP: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CONNECTING: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_DISCONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_DISCONNECTING: Int32
}
