// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("android.bluetooth.BluetoothStatusCodes")
open class BluetoothStatusCodes: JavaObject {

}
extension JavaClass<BluetoothStatusCodes> {
  @JavaStaticField(isFinal: true)
  public var ERROR_BLUETOOTH_NOT_ALLOWED: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_BLUETOOTH_NOT_ENABLED: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_DEVICE_NOT_BONDED: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_GATT_WRITE_NOT_ALLOWED: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_GATT_WRITE_REQUEST_BUSY: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_MISSING_BLUETOOTH_CONNECT_PERMISSION: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_PROFILE_SERVICE_NOT_BOUND: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_UNKNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var FEATURE_NOT_CONFIGURED: Int32

  @JavaStaticField(isFinal: true)
  public var FEATURE_NOT_SUPPORTED: Int32

  @JavaStaticField(isFinal: true)
  public var FEATURE_SUPPORTED: Int32

  @JavaStaticField(isFinal: true)
  public var SUCCESS: Int32
}
