// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension BluetoothClass.Device {
  @JavaClass("android.bluetooth.BluetoothClass$Device$Major")
  open class Major: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
  }
}
extension JavaClass<BluetoothClass.Device.Major> {
  @JavaStaticField(isFinal: true)
  public var AUDIO_VIDEO: Int32

  @JavaStaticField(isFinal: true)
  public var COMPUTER: Int32

  @JavaStaticField(isFinal: true)
  public var HEALTH: Int32

  @JavaStaticField(isFinal: true)
  public var IMAGING: Int32

  @JavaStaticField(isFinal: true)
  public var MISC: Int32

  @JavaStaticField(isFinal: true)
  public var NETWORKING: Int32

  @JavaStaticField(isFinal: true)
  public var PERIPHERAL: Int32

  @JavaStaticField(isFinal: true)
  public var PHONE: Int32

  @JavaStaticField(isFinal: true)
  public var TOY: Int32

  @JavaStaticField(isFinal: true)
  public var UNCATEGORIZED: Int32

  @JavaStaticField(isFinal: true)
  public var WEARABLE: Int32
}
