// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.BluetoothHidDevice", implements: BluetoothProfile.self)
open class BluetoothHidDevice: JavaObject {
  @JavaMethod
  open func getConnectionState(_ arg0: BluetoothDevice?) -> Int32

  @JavaMethod
  open func disconnect(_ arg0: BluetoothDevice?) -> Bool

  @JavaMethod
  open func connect(_ arg0: BluetoothDevice?) -> Bool

  @JavaMethod
  open func unregisterApp() -> Bool

  @JavaMethod
  open func sendReport(_ arg0: BluetoothDevice?, _ arg1: Int32, _ arg2: [Int8]) -> Bool

  @JavaMethod
  open func replyReport(_ arg0: BluetoothDevice?, _ arg1: Int8, _ arg2: Int8, _ arg3: [Int8]) -> Bool

  @JavaMethod
  open func getConnectedDevices() -> List<BluetoothDevice>!

  @JavaMethod
  open func getDevicesMatchingConnectionStates(_ arg0: [Int32]) -> List<BluetoothDevice>!

  @JavaMethod
  open func reportError(_ arg0: BluetoothDevice?, _ arg1: Int8) -> Bool
}
extension JavaClass<BluetoothHidDevice> {
  @JavaStaticField(isFinal: true)
  public var ACTION_CONNECTION_STATE_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ERROR_RSP_INVALID_PARAM: Int8

  @JavaStaticField(isFinal: true)
  public var ERROR_RSP_INVALID_RPT_ID: Int8

  @JavaStaticField(isFinal: true)
  public var ERROR_RSP_NOT_READY: Int8

  @JavaStaticField(isFinal: true)
  public var ERROR_RSP_SUCCESS: Int8

  @JavaStaticField(isFinal: true)
  public var ERROR_RSP_UNKNOWN: Int8

  @JavaStaticField(isFinal: true)
  public var ERROR_RSP_UNSUPPORTED_REQ: Int8

  @JavaStaticField(isFinal: true)
  public var PROTOCOL_BOOT_MODE: Int8

  @JavaStaticField(isFinal: true)
  public var PROTOCOL_REPORT_MODE: Int8

  @JavaStaticField(isFinal: true)
  public var REPORT_TYPE_FEATURE: Int8

  @JavaStaticField(isFinal: true)
  public var REPORT_TYPE_INPUT: Int8

  @JavaStaticField(isFinal: true)
  public var REPORT_TYPE_OUTPUT: Int8

  @JavaStaticField(isFinal: true)
  public var SUBCLASS1_COMBO: Int8

  @JavaStaticField(isFinal: true)
  public var SUBCLASS1_KEYBOARD: Int8

  @JavaStaticField(isFinal: true)
  public var SUBCLASS1_MOUSE: Int8

  @JavaStaticField(isFinal: true)
  public var SUBCLASS1_NONE: Int8

  @JavaStaticField(isFinal: true)
  public var SUBCLASS2_CARD_READER: Int8

  @JavaStaticField(isFinal: true)
  public var SUBCLASS2_DIGITIZER_TABLET: Int8

  @JavaStaticField(isFinal: true)
  public var SUBCLASS2_GAMEPAD: Int8

  @JavaStaticField(isFinal: true)
  public var SUBCLASS2_JOYSTICK: Int8

  @JavaStaticField(isFinal: true)
  public var SUBCLASS2_REMOTE_CONTROL: Int8

  @JavaStaticField(isFinal: true)
  public var SUBCLASS2_SENSING_DEVICE: Int8

  @JavaStaticField(isFinal: true)
  public var SUBCLASS2_UNCATEGORIZED: Int8

  @JavaStaticField(isFinal: true)
  public var A2DP: Int32

  @JavaStaticField(isFinal: true)
  public var CSIP_SET_COORDINATOR: Int32

  @JavaStaticField(isFinal: true)
  public var EXTRA_PREVIOUS_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_STATE: String

  @JavaStaticField(isFinal: true)
  public var GATT: Int32

  @JavaStaticField(isFinal: true)
  public var GATT_SERVER: Int32

  @JavaStaticField(isFinal: true)
  public var HAP_CLIENT: Int32

  @JavaStaticField(isFinal: true)
  public var HEADSET: Int32

  @JavaStaticField(isFinal: true)
  public var HEALTH: Int32

  @JavaStaticField(isFinal: true)
  public var HEARING_AID: Int32

  @JavaStaticField(isFinal: true)
  public var HID_DEVICE: Int32

  @JavaStaticField(isFinal: true)
  public var LE_AUDIO: Int32

  @JavaStaticField(isFinal: true)
  public var SAP: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CONNECTING: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_DISCONNECTED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_DISCONNECTING: Int32
}
