// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension BluetoothAdapter {
  @JavaInterface("android.bluetooth.BluetoothAdapter$LeScanCallback")
  public struct LeScanCallback {
  @JavaMethod
  public func onLeScan(_ arg0: BluetoothDevice?, _ arg1: Int32, _ arg2: [Int8])
  }
}
