// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension BluetoothCodecConfig {
  @JavaClass("android.bluetooth.BluetoothCodecConfig$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func setCodecType(_ arg0: Int32) -> BluetoothCodecConfig.Builder!

  @JavaMethod
  open func setCodecPriority(_ arg0: Int32) -> BluetoothCodecConfig.Builder!

  @JavaMethod
  open func setSampleRate(_ arg0: Int32) -> BluetoothCodecConfig.Builder!

  @JavaMethod
  open func setBitsPerSample(_ arg0: Int32) -> BluetoothCodecConfig.Builder!

  @JavaMethod
  open func setChannelMode(_ arg0: Int32) -> BluetoothCodecConfig.Builder!

  @JavaMethod
  open func setCodecSpecific1(_ arg0: Int64) -> BluetoothCodecConfig.Builder!

  @JavaMethod
  open func setCodecSpecific2(_ arg0: Int64) -> BluetoothCodecConfig.Builder!

  @JavaMethod
  open func setCodecSpecific3(_ arg0: Int64) -> BluetoothCodecConfig.Builder!

  @JavaMethod
  open func setCodecSpecific4(_ arg0: Int64) -> BluetoothCodecConfig.Builder!

  @JavaMethod
  open func setExtendedCodecType(_ arg0: BluetoothCodecType?) -> BluetoothCodecConfig.Builder!

  @JavaMethod
  open func build() -> BluetoothCodecConfig!
  }
}
