// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import AndroidOS
import JavaKit
import JavaRuntime
import JavaUtil

@JavaClass("android.bluetooth.BluetoothDevice", implements: Parcelable.self)
open class BluetoothDevice: JavaObject {
  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func getAddressType() -> Int32

  @JavaMethod
  open func getAlias() -> String

  @JavaMethod
  open func setAlias(_ arg0: String) -> Int32

  @JavaMethod
  open func createBond() -> Bool

  @JavaMethod
  open func getBondState() -> Int32

  @JavaMethod
  open func getBluetoothClass() -> BluetoothClass!

  @JavaMethod
  open func getUuids() -> [ParcelUuid?]

  @JavaMethod
  open func fetchUuidsWithSdp() -> Bool

  @JavaMethod
  open func setPin(_ arg0: [Int8]) -> Bool

  /**
   Connect to GATT Server hosted by this device. Caller acts as GATT client. The callback is used to deliver results to Caller, such as connection status as well as any further GATT client operations. The method returns a BluetoothGatt instance. You can use BluetoothGatt to conduct GATT client operations.
   For apps targeting Build.VERSION_CODES.S or or higher, this requires the Manifest.permission.BLUETOOTH_CONNECT permission which can be gained with Activity.requestPermissions(String[], int).
   
   Requires `Manifest.permission.BLUETOOTH_CONNECT`
   */
  @JavaMethod
  public func connectGatt(
    context: AndroidContent.Context?,
    autoConnect: Bool,
    callback: BluetoothGattCallback?
  ) -> BluetoothGatt!

  /**
   Connect to GATT Server hosted by this device. Caller acts as GATT client. The callback is used to deliver results to Caller, such as connection status as well as any further GATT client operations. The method returns a BluetoothGatt instance. You can use BluetoothGatt to conduct GATT client operations.
   For apps targeting `Build.VERSION_CODES.S` or or higher, this requires the `Manifest.permission.BLUETOOTH_CONNECT` permission which can be gained with Activity.requestPermissions(String[], int).
   
   Requires `Manifest.permission.BLUETOOTH_CONNECT`
   */
  @JavaMethod
  internal func connectGatt(
    _ context: AndroidContent.Context?,
    _ autoConnect: Bool,
    _ callback: BluetoothGattCallback?,
    _ transport: Int32
  ) -> BluetoothGatt!
    
  /// Connect to GATT Server hosted by this device. Caller acts as GATT client. The callback is used to deliver results to Caller, such as connection status as well as any further GATT client operations.
  ///
  /// - Parameter context: The running app's context.
  ///
  /// - Parameter autoConnect: Whether to directly connect to the remote device (false) or to automatically connect as soon as the remote device becomes available (true).
  ///
  /// - Parameter callback: GATT callback handler that will receive asynchronous callbacks.
  ///
  /// - Parameter transport: Preferred transport for GATT connections to remote dual-mode devices
  ///
  /// - Returns: The method returns a ``BluetoothGatt`` instance.
  ///
  /// - Note: Requires `Manifest.permission.BLUETOOTH_CONNECT`
  public func connectGatt(
      context: AndroidContent.Context,
      autoConnect: Bool = false,
      callback: BluetoothGattCallback,
      transport: BluetoothTransport = .auto
  ) -> BluetoothGatt! {
      connectGatt(context, autoConnect, callback, transport.rawValue)
  }

  /**
   Connect to GATT Server hosted by this device. Caller acts as GATT client. The callback is used to deliver results to Caller, such as connection status as well as any further GATT client operations. The method returns a BluetoothGatt instance. You can use BluetoothGatt to conduct GATT client operations.
   For apps targeting Build.VERSION_CODES.S or or higher, this requires the Manifest.permission.BLUETOOTH_CONNECT permission which can be gained with Activity.requestPermissions(String[], int).
   
   Requires Manifest.permission.BLUETOOTH_CONNECT
   */
  @JavaMethod
  public func connectGatt(
    _ context: AndroidContent.Context?,
    _ autoConnect: Bool,
    _ callback: BluetoothGattCallback?,
    _ transport: BluetoothTransport,
    _ phy: Int32
  ) -> BluetoothGatt!

  @JavaMethod
  public func connectGatt(
    _ context: AndroidContent.Context?,
    _ autoConnect: Bool,
    _ callback: BluetoothGattCallback?,
    _ transport: Int,
    _ phy: Int32,
    _ handler: Handler?
  ) -> BluetoothGatt!
  
  @JavaMethod
  open func createL2capChannel(_ arg0: Int32) throws -> BluetoothSocket!

  @JavaMethod
  open func setPairingConfirmation(_ arg0: Bool) -> Bool

  @JavaMethod
  open func createRfcommSocketToServiceRecord(_ arg0: UUID?) throws -> BluetoothSocket!

  @JavaMethod
  open func createInsecureL2capChannel(_ arg0: Int32) throws -> BluetoothSocket!

  @JavaMethod
  open func createInsecureRfcommSocketToServiceRecord(_ arg0: UUID?) throws -> BluetoothSocket!

  @JavaMethod
  open func getName() -> String

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func getType() -> Int32

  @JavaMethod
  open func getAddress() -> String
}
extension JavaClass<BluetoothDevice> {
  @JavaStaticField(isFinal: true)
  public var ACTION_ACL_CONNECTED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_ACL_DISCONNECTED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_ACL_DISCONNECT_REQUESTED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_ALIAS_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_BOND_STATE_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_CLASS_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_FOUND: String

  @JavaStaticField(isFinal: true)
  public var ACTION_NAME_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_PAIRING_REQUEST: String

  @JavaStaticField(isFinal: true)
  public var ACTION_UUID: String

  @JavaStaticField(isFinal: true)
  public var ADDRESS_TYPE_ANONYMOUS: Int32

  @JavaStaticField(isFinal: true)
  public var ADDRESS_TYPE_PUBLIC: Int32

  @JavaStaticField(isFinal: true)
  public var ADDRESS_TYPE_RANDOM: Int32

  @JavaStaticField(isFinal: true)
  public var ADDRESS_TYPE_UNKNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var BOND_BONDED: Int32

  @JavaStaticField(isFinal: true)
  public var BOND_BONDING: Int32

  @JavaStaticField(isFinal: true)
  public var BOND_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<BluetoothDevice>!

  @JavaStaticField(isFinal: true)
  public var DEVICE_TYPE_CLASSIC: Int32

  @JavaStaticField(isFinal: true)
  public var DEVICE_TYPE_DUAL: Int32

  @JavaStaticField(isFinal: true)
  public var DEVICE_TYPE_LE: Int32

  @JavaStaticField(isFinal: true)
  public var DEVICE_TYPE_UNKNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR: Int32

  @JavaStaticField(isFinal: true)
  public var EXTRA_BOND_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_CLASS: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_DEVICE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_IS_COORDINATED_SET_MEMBER: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_NAME: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PAIRING_KEY: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PAIRING_VARIANT: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PREVIOUS_BOND_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_RSSI: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_TRANSPORT: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_UUID: String

  @JavaStaticField(isFinal: true)
  public var PAIRING_VARIANT_PASSKEY_CONFIRMATION: Int32

  @JavaStaticField(isFinal: true)
  public var PAIRING_VARIANT_PIN: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_LE_1M: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_LE_1M_MASK: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_LE_2M: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_LE_2M_MASK: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_LE_CODED: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_LE_CODED_MASK: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_OPTION_NO_PREFERRED: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_OPTION_S2: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_OPTION_S8: Int32

  @JavaStaticField(isFinal: true)
  public var TRANSPORT_AUTO: Int32

  @JavaStaticField(isFinal: true)
  public var TRANSPORT_BREDR: Int32

  @JavaStaticField(isFinal: true)
  public var TRANSPORT_LE: Int32

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
