// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension PeriodicAdvertisingParameters {
  @JavaClass("android.bluetooth.le.PeriodicAdvertisingParameters$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func setIncludeTxPower(_ arg0: Bool) -> PeriodicAdvertisingParameters.Builder!

  @JavaMethod
  open func setInterval(_ arg0: Int32) -> PeriodicAdvertisingParameters.Builder!

  @JavaMethod
  open func build() -> PeriodicAdvertisingParameters!
  }
}
