// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaKit
import JavaRuntime

@JavaClass("android.bluetooth.le.PeriodicAdvertisingParameters", implements: Parcelable.self)
open class PeriodicAdvertisingParameters: JavaObject {
  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func getInterval() -> Int32

  @JavaMethod
  open func getIncludeTxPower() -> Bool
}
extension JavaClass<PeriodicAdvertisingParameters> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<PeriodicAdvertisingParameters>!

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
