// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaKit
import JavaRuntime

@JavaClass("android.bluetooth.le.ScanResult", implements: Parcelable.self)
open class ScanResult: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: BluetoothDevice?, _ arg1: ScanRecord?, _ arg2: Int32, _ arg3: Int64, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: BluetoothDevice?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32, _ arg5: Int32, _ arg6: Int32, _ arg7: Int32, _ arg8: ScanRecord?, _ arg9: Int64, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func getDevice() -> BluetoothDevice!

  @JavaMethod
  open func isConnectable() -> Bool

  @JavaMethod
  open func isLegacy() -> Bool

  @JavaMethod
  open func getPrimaryPhy() -> Int32

  @JavaMethod
  open func getSecondaryPhy() -> Int32

  @JavaMethod
  open func getScanRecord() -> ScanRecord!

  @JavaMethod
  open func getRssi() -> Int32

  @JavaMethod
  open func getTimestampNanos() -> Int64

  @JavaMethod
  open func getDataStatus() -> Int32

  @JavaMethod
  open func getAdvertisingSid() -> Int32

  @JavaMethod
  open func getTxPower() -> Int32

  @JavaMethod
  open func getPeriodicAdvertisingInterval() -> Int32

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32
}
extension JavaClass<ScanResult> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<ScanResult>!

  @JavaStaticField(isFinal: true)
  public var DATA_COMPLETE: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TRUNCATED: Int32

  @JavaStaticField(isFinal: true)
  public var PERIODIC_INTERVAL_NOT_PRESENT: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_UNUSED: Int32

  @JavaStaticField(isFinal: true)
  public var SID_NOT_PRESENT: Int32

  @JavaStaticField(isFinal: true)
  public var TX_POWER_NOT_PRESENT: Int32

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
