// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import SwiftJava
import CSwiftJavaJNI

/// Bluetooth LE scan settings are passed to `BluetoothLeScanner.startScan()` to define the parameters for the scan.
///
/// - Since: API Level 21
@available(Android 21, *)
@JavaClass("android.bluetooth.le.ScanSettings", implements: Parcelable.self)
open class ScanSettings: JavaObject {
  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func getScanMode() -> Int32

  @JavaMethod
  open func getCallbackType() -> Int32

  @JavaMethod
  open func getScanResultType() -> Int32

  @JavaMethod
  open func getLegacy() -> Bool

  @JavaMethod
  open func getPhy() -> Int32

  @JavaMethod
  open func getReportDelayMillis() -> Int64
}
extension JavaClass<ScanSettings> {
  @JavaStaticField(isFinal: true)
  public var AUTO_BATCH_MIN_REPORT_DELAY_MILLIS: Int64

  @JavaStaticField(isFinal: true)
  public var CALLBACK_TYPE_ALL_MATCHES: Int32

  @JavaStaticField(isFinal: true)
  public var CALLBACK_TYPE_ALL_MATCHES_AUTO_BATCH: Int32

  @JavaStaticField(isFinal: true)
  public var CALLBACK_TYPE_FIRST_MATCH: Int32

  @JavaStaticField(isFinal: true)
  public var CALLBACK_TYPE_MATCH_LOST: Int32

  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<ScanSettings>!

  @JavaStaticField(isFinal: true)
  public var MATCH_MODE_AGGRESSIVE: Int32

  @JavaStaticField(isFinal: true)
  public var MATCH_MODE_STICKY: Int32

  @JavaStaticField(isFinal: true)
  public var MATCH_NUM_FEW_ADVERTISEMENT: Int32

  @JavaStaticField(isFinal: true)
  public var MATCH_NUM_MAX_ADVERTISEMENT: Int32

  @JavaStaticField(isFinal: true)
  public var MATCH_NUM_ONE_ADVERTISEMENT: Int32

  @JavaStaticField(isFinal: true)
  public var PHY_LE_ALL_SUPPORTED: Int32

  @JavaStaticField(isFinal: true)
  public var SCAN_MODE_BALANCED: Int32

  @JavaStaticField(isFinal: true)
  public var SCAN_MODE_LOW_LATENCY: Int32

  @JavaStaticField(isFinal: true)
  public var SCAN_MODE_LOW_POWER: Int32

  @JavaStaticField(isFinal: true)
  public var SCAN_MODE_OPPORTUNISTIC: Int32

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
