// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import AndroidUtil
import JavaKit
import JavaKitCollection
import JavaRuntime
import JavaUtil

@JavaClass("android.bluetooth.le.ScanRecord")
open class ScanRecord: JavaObject {
  @JavaMethod
  open func getTxPowerLevel() -> Int32

  @JavaMethod
  open func getAdvertiseFlags() -> Int32

  @JavaMethod
  open func getServiceUuids() -> List<ParcelUuid>!

  @JavaMethod
  open func getServiceData(_ arg0: ParcelUuid?) -> [Int8]

  @JavaMethod
  open func getServiceData() -> Map<ParcelUuid, JavaArray>!

  @JavaMethod
  open func getDeviceName() -> String

  @JavaMethod
  open func getServiceSolicitationUuids() -> List<ParcelUuid>!

  @JavaMethod
  open func getManufacturerSpecificData(_ arg0: Int32) -> [Int8]

  @JavaMethod
  open func getManufacturerSpecificData() -> SparseArray<JavaArray>!

  @JavaMethod
  open func getAdvertisingDataMap() -> Map<JavaInteger, JavaArray>!

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  internal func getBytes() -> [Int8]

  public var bytes: [UInt8] {
      unsafeBitCast(getBytes(), to: [UInt8].self)
  }
}
extension JavaClass<ScanRecord> {
  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_3D_INFORMATION_DATA: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_ADVERTISING_INTERVAL: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_ADVERTISING_INTERVAL_LONG: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_APPEARANCE: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_BIG_INFO: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_BROADCAST_CODE: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_CHANNEL_MAP_UPDATE_INDICATION: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_CLASS_OF_DEVICE: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_DEVICE_ID: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_FLAGS: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_INDOOR_POSITIONING: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_LE_BLUETOOTH_DEVICE_ADDRESS: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_LE_ROLE: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_LE_SECURE_CONNECTIONS_CONFIRMATION_VALUE: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_LE_SECURE_CONNECTIONS_RANDOM_VALUE: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_LE_SUPPORTED_FEATURES: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_LOCAL_NAME_COMPLETE: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_LOCAL_NAME_SHORT: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_MANUFACTURER_SPECIFIC_DATA: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_MESH_BEACON: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_MESH_MESSAGE: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_PB_ADV: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_PUBLIC_TARGET_ADDRESS: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_RANDOM_TARGET_ADDRESS: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_RESOLVABLE_SET_IDENTIFIER: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SECURITY_MANAGER_OUT_OF_BAND_FLAGS: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SERVICE_DATA_128_BIT: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SERVICE_DATA_16_BIT: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SERVICE_DATA_32_BIT: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SERVICE_SOLICITATION_UUIDS_128_BIT: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SERVICE_SOLICITATION_UUIDS_16_BIT: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SERVICE_SOLICITATION_UUIDS_32_BIT: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SERVICE_UUIDS_128_BIT_COMPLETE: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SERVICE_UUIDS_128_BIT_PARTIAL: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SERVICE_UUIDS_16_BIT_COMPLETE: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SERVICE_UUIDS_16_BIT_PARTIAL: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SERVICE_UUIDS_32_BIT_COMPLETE: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SERVICE_UUIDS_32_BIT_PARTIAL: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SIMPLE_PAIRING_HASH_C: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SIMPLE_PAIRING_HASH_C_256: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SIMPLE_PAIRING_RANDOMIZER_R: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SIMPLE_PAIRING_RANDOMIZER_R_256: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_SLAVE_CONNECTION_INTERVAL_RANGE: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_TRANSPORT_DISCOVERY_DATA: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_TX_POWER_LEVEL: Int32

  @JavaStaticField(isFinal: true)
  public var DATA_TYPE_URI: Int32
}
