// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension ScanSettings {
  @JavaClass("android.bluetooth.le.ScanSettings$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func setScanMode(_ arg0: Int32) -> ScanSettings.Builder!

  @JavaMethod
  open func setCallbackType(_ arg0: Int32) -> ScanSettings.Builder!

  @JavaMethod
  open func setReportDelay(_ arg0: Int64) -> ScanSettings.Builder!

  @JavaMethod
  open func setNumOfMatches(_ arg0: Int32) -> ScanSettings.Builder!

  @JavaMethod
  open func setMatchMode(_ arg0: Int32) -> ScanSettings.Builder!

  @JavaMethod
  open func setLegacy(_ arg0: Bool) -> ScanSettings.Builder!

  @JavaMethod
  open func setPhy(_ arg0: Int32) -> ScanSettings.Builder!

  @JavaMethod
  open func build() -> ScanSettings!
  }
}
