// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.bluetooth.le.TransportBlock", implements: Parcelable.self)
open class TransportBlock: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: [Int8], environment: JNIEnvironment? = nil)

  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func totalBytes() -> Int32

  @JavaMethod
  open func getOrgId() -> Int32

  @JavaMethod
  open func getTdsFlags() -> Int32

  @JavaMethod
  open func getTransportData() -> [Int8]

  @JavaMethod
  open func getTransportDataLength() -> Int32

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func toByteArray() -> [Int8]
}
extension JavaClass<TransportBlock> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<TransportBlock>!

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
